// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type OfficePage = {
  /**
   * Velg kontortype
   */
  type?:
    | {
        /**
         * Selected
         */
        _selected: "LOKAL";

        /**
         * Lokalkontor
         */
        LOKAL: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "HMS";

        /**
         * Hjelpemiddelsentral
         */
        HMS: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "ALS";

        /**
         * Arbeidslivssenter
         */
        ALS: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "OPPFUTLAND";

        /**
         * NAV Utland og fellestjenester
         */
        OPPFUTLAND: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "KONTROLL";

        /**
         * NAV Kontroll
         */
        KONTROLL: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "KLAGE";

        /**
         * NAV Klageinstans
         */
        KLAGE: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "OKONOMI";

        /**
         * NAV Økonomi Stønad
         */
        OKONOMI: Record<string, unknown>;
      };

  /**
   * Kontordata
   */
  officeNorgData:
    | {
        /**
         * Selected
         */
        _selected: "data";

        /**
         * Data
         */
        data: {
          /**
           * Checksum
           */
          checksum?: string;

          /**
           * Navn
           */
          navn: string;

          /**
           * EnhetNr
           */
          enhetNr: string;

          /**
           * Type
           */
          type: string;

          /**
           * Status
           */
          status?: string;

          /**
           * Organisasjonsnummer
           */
          organisasjonsnummer?: string;

          /**
           * Under Etablering Dato
           */
          underEtableringDato?: string;

          /**
           * Aktiveringsdato
           */
          aktiveringsdato?: string;

          /**
           * Under Avvikling Dato
           */
          underAvviklingDato?: string;

          /**
           * Nedleggelsesdato
           */
          nedleggelsesdato?: string;

          /**
           * Sosiale Tjenester
           */
          sosialeTjenester?: string;

          /**
           * Spesielle opplysninger
           */
          spesielleOpplysninger?: string;

          /**
           * Beliggenhet
           */
          beliggenhet?: {
            /**
             * Type
             */
            type?: string;

            /**
             * Postnummer
             */
            postnummer?: string;

            /**
             * Poststed
             */
            poststed?: string;

            /**
             * Gatenavn
             */
            gatenavn?: string;

            /**
             * Husnummer
             */
            husnummer?: string;

            /**
             * Husbokstav
             */
            husbokstav?: string;

            /**
             * Adresse tilleggsnavn
             */
            adresseTilleggsnavn?: string;
          };

          /**
           * Postadresse
           */
          postadresse?: {
            /**
             * Type
             */
            type?: string;

            /**
             * Postnummer
             */
            postnummer?: string;

            /**
             * Poststed
             */
            poststed?: string;

            /**
             * Gatenavn
             */
            gatenavn?: string;

            /**
             * Husnummer
             */
            husnummer?: string;

            /**
             * Husbokstav
             */
            husbokstav?: string;

            /**
             * Adresse tilleggsnavn
             */
            adresseTilleggsnavn?: string;

            /**
             * Postboksnummer
             */
            postboksnummer?: string;

            /**
             * Postboksanlegg
             */
            postboksanlegg?: string;
          };

          /**
           * Brukerkontakt
           */
          brukerkontakt?: {
            /**
             * Publikumsmottak
             */
            publikumsmottak?: Array<{
              /**
               * Besøksadresse
               */
              besoeksadresse?: {
                /**
                 * Type
                 */
                type?: string;

                /**
                 * Postnummer
                 */
                postnummer?: string;

                /**
                 * Poststed
                 */
                poststed?: string;

                /**
                 * Gatenavn
                 */
                gatenavn?: string;

                /**
                 * Husnummer
                 */
                husnummer?: string;

                /**
                 * Husbokstav
                 */
                husbokstav?: string;

                /**
                 * Adresse Tilleggsnavn
                 */
                adresseTilleggsnavn?: string;
              };

              /**
               * Åpningstider
               */
              aapningstider?: Array<{
                /**
                 * Dag
                 */
                dag?: string;

                /**
                 * Dato
                 */
                dato?: string;

                /**
                 * Fra
                 */
                fra?: string;

                /**
                 * Til
                 */
                til?: string;

                /**
                 * Kommentar
                 */
                kommentar?: string;

                /**
                 * Stengt
                 */
                stengt?: string;

                /**
                 * Kun timeavtale
                 */
                kunTimeavtale?: string;
              }>;

              /**
               * Stedsbeskrivelse
               */
              stedsbeskrivelse?: string;

              /**
               * Adkomstbeskrivelse
               */
              adkomstbeskrivelse?: string;
            }>;

            /**
             * Publikumskanaler
             */
            publikumskanaler?: Array<{
              /**
               * Beskrivelse
               */
              beskrivelse?: string;

              /**
               * Telefon
               */
              telefon?: string;

              /**
               * E-post
               */
              epost?: string;

              /**
               * Sortering
               */
              sortOrder?: string;
            }>;

            /**
             * Brukertjenestetilbud
             */
            brukertjenesteTilbud?: {
              /**
               * Tjenester
               */
              tjenester?: Array<{
                /**
                 * Type
                 */
                type?: string;
              }>;

              /**
               * Ytterligere informasjon
               */
              ytterligereInformasjon?: string;
            };

            /**
             * Informasjon utbetalinger
             */
            informasjonUtbetalinger?: string;

            /**
             * Sosialhjelp
             */
            sosialhjelp?: {
              /**
               * Digitale søknader
               */
              digitaleSoeknader?: Array<{
                /**
                 * Lenke
                 */
                lenke?: string;

                /**
                 * Lenketekst
                 */
                lenketekst?: string;
              }>;

              /**
               * Papirsøknad informasjon
               */
              papirsoeknadInformasjon?: string;
            };

            /**
             * Skriftspraak
             */
            skriftspraak?: string;
          };
        };
      };
}
