// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicAlertPartConfig {
  /**
   * Innhold
   */
  content?: string;

  /**
   * Type
   */
  type?: "info" | "suksess" | "advarsel" | "feil";

  /**
   * Størrelse
   */
  size?: "medium" | "small";

  /**
   * Uten bakgrunn (inline)
   */
  inline: boolean;

  /**
   * Margin på containeren
   */
  margin?: string;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
