// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicAlertConfig {
  /**
   * Type
   */
  type?: "info" | "suksess" | "advarsel" | "feil";

  /**
   * Inline
   */
  inline: "true" | "false";

  /**
   * Innhold
   */
  content?: string;

  /**
   * Margin på containeren
   */
  margin?: string;
}
