// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LinkInternal {
  /**
   * Innhold det skal lenkes til
   */
  target: string;

  /**
   * Lenketekst (hvis tom vil tittel på innholdet vises)
   */
  text?: string;
}
