// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SectionPage {
  /**
   * Hvor mange elementer i undermenyene er tillatt
   */
  nrNews?: number;

  /**
   * Velg innhold
   */
  newsContents?: string;

  /**
   * Url til flere nyheter
   */
  moreNewsUrl?: string;

  /**
   * Hvor mange elementer i undermenyene er tillatt
   */
  nrNTK?: number;

  /**
   * Velg innhold
   */
  ntkContents?: string;

  /**
   * Hvor mange elementer i undermenyene er tillatt
   */
  nrSC?: number;

  /**
   * Velg innhold
   */
  scContents?: string;

  /**
   * Velg innhold
   */
  breaking_news?: Array<string>;
}
