// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CmsMenu {
  /**
   * Menu item key
   */
  menuKey?: string;

  /**
   * Menu item related content
   */
  content?: string;
}
