// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SituationFlexColsConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Anker-id
   */
  anchorId?: string;

  /**
   * Ikke vis under innhold
   */
  hideFromInternalNavigation: boolean;

  /**
   * Toggle "kopier lenke" knapp
   */
  toggleCopyButton: boolean;

  /**
   * For varehylle
   */
  productShelf?:
    | {
        /**
         * Selected
         */
        _selected: "produkter";

        /**
         * Produkter
         */
        produkter: {
          /**
           * Prioritering
           */
          priority?: "priority1" | "priority2" | "priority3";
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "samarbeidspartner";

        /**
         * Samarbeidspartner
         */
        samarbeidspartner: Record<string, unknown>;
      };

  /**
   * Antall kolonner ved full skjermbredde
   */
  numCols?: number;

  /**
   * Justering
   */
  justifyContent?: "flex-start" | "center" | "flex-end";

  /**
   * Bakgrunnsfarge
   */
  bgColor?: {
    /**
     * Velg farge
     */
    color: string;
  };
}
