// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ContactOptionPartConfig {
  /**
   * Kontakt-oss kanaler
   */
  contactOptions:
    | {
        /**
         * Selected
         */
        _selected: "chat";

        /**
         * Chat
         */
        chat: {
          /**
           * Overstyr ingress
           */
          ingress?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "write";

        /**
         * Skriv til oss
         */
        write: {
          /**
           * Overstyr tittel
           */
          title?: string;

          /**
           * Overstyr URL
           */
          url?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "call";

        /**
         * Ring oss
         */
        call: {
          /**
           * Velg telefonnummer
           */
          sharedContactInformation?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;

          /**
           * -
           */
          phoneNumber?: undefined;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "custom";

        /**
         * Egentilpasset
         */
        custom: {
          /**
           * Tittel
           */
          title: string;

          /**
           * Icon
           */
          icon: "facebook" | "linkedin";

          /**
           * Url
           */
          url: string;

          /**
           * Ingress
           */
          ingress?: string;
        };
      };

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
