// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ToolsPage = {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Målgruppe
   */
  audience:
    | {
        /**
         * Selected
         */
        _selected: "person";

        /**
         * Privatperson
         */
        person: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "employer";

        /**
         * Arbeidsgiver
         */
        employer: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "provider";

        /**
         * Samarbeidspartner
         */
        provider: {
          /**
           * Velg underkategorier
           */
          provider_audience: Array<"doctor" | "municipality_employed" | "optician" | "administrator" | "measures_organizer" | "aid_supplier" | "other"> | "doctor" | "municipality_employed" | "optician" | "administrator" | "measures_organizer" | "aid_supplier" | "other";
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "other";

        /**
         * Annet
         */
        other: Record<string, unknown>;
      };

  /**
   * Kategorier
   */
  taxonomy?: Array<"calculator" | "navigator"> | "calculator" | "navigator";

  /**
   * Områdekategori
   */
  area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment"> | "health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment";

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Videresend alle besøk til annen url:
   */
  externalProductUrl?: string;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath: string;

  /**
   * Velg eier
   */
  owner: Array<"arbeids_og_tjenesteavdelingen" | "arbeidsavdelingen_arbeid_helse" | "arbeidsavdelingen_arbeidsgivertjenester" | "arbeidsavdelingen_arbeidsmarkedstiltak" | "arbeidsavdelingen_arbeidsoppfolging" | "avdeling for brukeropplevelse" | "hr_avdelingen" | "direktoratet" | "juridisk_avdeling" | "kommunikasjonsavdelingen" | "kunnskapsavdelingen" | "statistikk" | "klageinstans" | "it_avdelingen" | "velferdsavdelingen_hjelpemidler" | "velferdsavdelingen_sosiale_tjenester" | "ytelsesavdelingen" | "ytelsesavdelingen_arbeidsavklaringspenger" | "ytelsesavdelingen_arbeidsytelser" | "ytelsesavdelingen_familieytelser" | "ytelsesavdelingen_helseytelser" | "ytelsesavdelingen_kontroll" | "ytelsesavdelingen_pensjon" | "okonomi" | "annet" | "arbeidslivssenter" | "hjelpemiddelsentralen" | "hjelpemidler_og_tilrettelegging" | "fylke" | "kontaktsenteret" | "min_side" | "team_personbruker" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet"> | "arbeids_og_tjenesteavdelingen" | "arbeidsavdelingen_arbeid_helse" | "arbeidsavdelingen_arbeidsgivertjenester" | "arbeidsavdelingen_arbeidsmarkedstiltak" | "arbeidsavdelingen_arbeidsoppfolging" | "avdeling for brukeropplevelse" | "hr_avdelingen" | "direktoratet" | "juridisk_avdeling" | "kommunikasjonsavdelingen" | "kunnskapsavdelingen" | "statistikk" | "klageinstans" | "it_avdelingen" | "velferdsavdelingen_hjelpemidler" | "velferdsavdelingen_sosiale_tjenester" | "ytelsesavdelingen" | "ytelsesavdelingen_arbeidsavklaringspenger" | "ytelsesavdelingen_arbeidsytelser" | "ytelsesavdelingen_familieytelser" | "ytelsesavdelingen_helseytelser" | "ytelsesavdelingen_kontroll" | "ytelsesavdelingen_pensjon" | "okonomi" | "annet" | "arbeidslivssenter" | "hjelpemiddelsentralen" | "hjelpemidler_og_tilrettelegging" | "fylke" | "kontaktsenteret" | "min_side" | "team_personbruker" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet";

  /**
   * Velg forvalter
   */
  "managed-by"?: Array<"arbeid_ytelser_styringsenhet" | "arbeidslivssenter" | "digisos" | "familie_pensjonsytelser_styringsenhet" | "fylke" | "hjelpemiddelsentralen" | "hjelpemidler_styringsenhet" | "kjernegruppe_aap" | "kjernegruppe_dagpenger" | "kjernegruppe_ekspertbistand" | "kjernegruppe_familie" | "kjernegruppe_hjelpemidler" | "kjernegruppe_medlemskap" | "kjernegruppe_oppfolging" | "kjernegruppe_ortopediske_hjelpemidler" | "kjernegruppe_pensjon" | "kjernegruppe_sosiale_tjenester" | "kjernegruppe_spraktolk" | "kjernegruppe_sykepenger" | "kjernegruppe_tiltak" | "kjernegruppe_tiltakspenger" | "kjernegruppe_uforetrygd" | "kjernegruppe_yrkesskade" | "nav_kontaktsenter_styringsenhet" | "team_minside" | "team_navno" | "po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver"> | "arbeid_ytelser_styringsenhet" | "arbeidslivssenter" | "digisos" | "familie_pensjonsytelser_styringsenhet" | "fylke" | "hjelpemiddelsentralen" | "hjelpemidler_styringsenhet" | "kjernegruppe_aap" | "kjernegruppe_dagpenger" | "kjernegruppe_ekspertbistand" | "kjernegruppe_familie" | "kjernegruppe_hjelpemidler" | "kjernegruppe_medlemskap" | "kjernegruppe_oppfolging" | "kjernegruppe_ortopediske_hjelpemidler" | "kjernegruppe_pensjon" | "kjernegruppe_sosiale_tjenester" | "kjernegruppe_spraktolk" | "kjernegruppe_sykepenger" | "kjernegruppe_tiltak" | "kjernegruppe_tiltakspenger" | "kjernegruppe_uforetrygd" | "kjernegruppe_yrkesskade" | "nav_kontaktsenter_styringsenhet" | "team_minside" | "team_navno" | "po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver";

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string> | string;
};
