// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface IntermediateStepData {
  /**
   * Redaksjonelt innhold ovenfor valgene
   */
  editorial?: string;

  /**
   * Steg
   */
  steps: Array<{
    /**
     * Tittel på valget
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;

    /**
     * Ekstern URL til søknad eller liknende
     */
    externalUrl?: string;

    /**
     * Redaksjonelt innhold ovenfor valgene
     */
    editorial?: string;

    /**
     * Steg
     */
    steps: Array<{
      /**
       * Tittel på valget
       */
      label: string;

      /**
       * Ekstra forklaring
       */
      explanation?: string;

      /**
       * Ekstern URL til søknad eller liknende
       */
      externalUrl?: string;
    }>;
  }>;
}
