// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface IntermediateStepData {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Målgruppe
   */
  audience: "person" | "employer" | "provider";

  /**
   * Områdekategori
   */
  area: Array<"work" | "family" | "health" | "accessibility" | "pension" | "social_counselling" | "municipality" | "other">;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath: string;

  /**
   * Valg for steg
   */
  stepOptions: Array<{
    /**
     * Tittel på valget
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;

    /**
     * Neste steg
     */
    nextStepReference?: string;
  }>;
}
