// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FormDetails {
  /**
   * Skjemanummer
   */
  formNumbers?: Array<string>;

  /**
   * Tittel
   */
  title?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Variasjoner
   */
  formType:
    | {
        /**
         * Selected
         */
        _selected: "application";

        /**
         * Søknad / skjema
         */
        application: {

          variations?: Array<{
            /**
             * Knappetekst
             */
            label: string;

            /**
             * URL til skjema
             */
            url: string;

            /**
             * Søknads- eller skjematype
             */
            type: "digital" | "paper" | "addendum_digital" | "addendum_paper";
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "complaint";

        /**
         * Klage- og ankevariasjoner
         */
        complaint: {
          /**
           * Klage- og ankevariasjoner
           */
          variations?: Array<{
            /**
             * URL til skjema
             */
            url: string;

            /**
             * Knappetekst
             */
            label: string;

            /**
             * Klage- eller anketype
             */
            type: "complaint" | "appeal" | "addendum";
          }>;
        };
      };
}
