// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface OfficeEditorialDetailPartConfig {
  /**
   * Velg detaljinformasjon
   */
  detailType: "serviceInformation" | "socialHelpLink" | "socialHelpPostalInformation" | "socialHelpPayoutInformation";
}
