// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageNavigationMenuPartConfig {
  /**
   * Overstyr lenketekster
   */
  anchorLinks?: Array<{
    /**
     * Anker-id
     */
    anchorId: string;

    /**
     * Lenketekst
     */
    linkText: string;
  }>;

  /**
   * Klikk "marker som klar" for å oppdatere menyen
   */
  dummyInputToPreventEmptyPartConfigDoNotRemove: "dummy";
}
