// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetailsData {
  /**
   * Type produktdetaljer
   */
  detailType: "rates" | "payout_dates" | "processing_times";
}
