// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Dummy {
  /**
   * Dummy field only used to force a content modify update
   */
  dummy?: string;
}
