plugins {
    id 'com.enonic.xp.app'
    id "com.github.node-gradle.node" version '7.1.0'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

node {
    version = '22.15.0'
    pnpmVersion = '11.1.3'
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    include xplibs.auditlog
    include xplibs.auth
    include xplibs.cluster
    include xplibs.common
    include xplibs.content
    include xplibs.context
    include xplibs.event
    include xplibs.grid
    include xplibs.io
    include xplibs.node
    include xplibs.portal
    include xplibs.project
    include xplibs.repo
    include xplibs.scheduler
    include xplibs.schema
    include xplibs.task
    include xplibs.value
    include xplibs.websocket
    include "com.enonic.lib:lib-cache:3.0.0"
    include "com.enonic.lib:lib-http-client:4.0.0"
    include "com.enonic.lib:lib-thymeleaf:3.0.0"
    include "com.enonic.lib:lib-urlredirect:4.0.0"
    webjar "org.webjars.npm:html-entities:2.5.2"
    webjar "org.webjars.npm:striptags:3.2.0"
    webjar "org.webjars.npm:dayjs:1.11.13"
}

tasks.register('babelJs', PnpmTask) {
    dependsOn 'pnpmInstall'
    dependsOn(processResources)

    args = ['run', 'build']
}


jar.dependsOn(babelJs)
