version: "3.7"
services:
  oidc-provider:
    container_name: oidc-provider
    image: "navikt/stub-oidc-provider:latest"
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      CALLBACK_URL: "http://localhost:5000/callback"
      ISSUER: "https://localhost:9000"

  oidc-provider-gui:
    container_name: oidc-provider-gui
    image: "navikt/pb-oidc-provider-gui:latest"
    ports:
      - "5000:5000"
    environment:
      REDIRECT_URL: "http://localhost:8080"
      AUTO_REDIRECT_TO_FRONTEND: "true"
    depends_on:
      - oidc-provider

  mocks:
    container_name: mocks
    image: "navikt/pb-nav-mocked:latest"
    ports:
      - "8095:8080"
    environment:
      CORS_ALLOWED_ORIGINS: "*"
      OIDC_ISSUER: "https://localhost:9000"
      OIDC_ACCEPTED_AUDIENCE: "stubOidcClient"
      OIDC_JWKS_URI: "http://oidc-provider:9000/certs"
    depends_on:
      - oidc-provider

  dekoratoren:
    container_name: dekoratoren
    image: "navikt/nav-dekoratoren:latest"
    ports:
      - "8100:8088"
    environment:
      BASE_URL: 'http://localhost:8100'
      BASE_URL_APP: "http://localhost:8100/dekoratoren"
      BASE_URL_ENONIC: 'https://www-q1.nav.no'
      API_INNLOGGINGSLINJE_URL: 'http://localhost:8095/innloggingslinje-api/auth'
      API_VARSELINNBOKS_URL: 'https://www-q0.nav.no/person/varselinnboks'
      BACKEND_MENY_URL: 'http://localhost:8100/dekoratoren/api/meny'
      BACKEND_SOK_URL: 'http://localhost:8100/dekoratoren/api/sok'
      MINSIDE_ARBEIDSGIVER_URL: 'https://arbeidsgiver-q.nav.no/min-side-arbeidsgiver/'
      LOGOUT_URL: 'http://localhost:5000/?logout'
      LOGIN_URL: 'http://localhost:5000'
    depends_on:
      - mocks

volumes:
  event-cache-data:
