packages:
  - test
  - test/e2e-tests
  - test/unit-tests
  - test/e2e-tests/.xp-test-data-app
catalog:
  '@anders-nom/babel-plugin-import-graphql-string': 2.8.1-12
  '@babel/cli': 7.29.7
  '@babel/core': 7.29.7
  '@babel/preset-env': 7.29.7
  '@babel/preset-typescript': 7.29.7
  '@enonic-types/core': 8.0.4
  '@enonic-types/global': 8.0.4
  '@enonic-types/lib-auditlog': 8.0.4
  '@enonic-types/lib-auth': 8.0.4
  '@enonic-types/lib-cluster': 8.0.4
  '@enonic-types/lib-common': 8.0.4
  '@enonic-types/lib-content': 8.0.4
  '@enonic-types/lib-context': 8.0.4
  '@enonic-types/lib-event': 8.0.4
  '@enonic-types/lib-grid': 8.0.4
  '@enonic-types/lib-io': 8.0.4
  '@enonic-types/lib-node': 8.0.4
  '@enonic-types/lib-portal': 8.0.4
  '@enonic-types/lib-project': 8.0.4
  '@enonic-types/lib-repo': 8.0.4
  '@enonic-types/lib-scheduler': 8.0.4
  '@enonic-types/lib-schema': 8.0.4
  '@enonic-types/lib-task': 8.0.4
  '@enonic-types/lib-value': 8.0.4
  '@enonic-types/lib-websocket': 8.0.4
  '@enonic/mock-xp': 1.0.0
  '@eslint/compat': 2.1.0
  '@eslint/eslintrc': 3.3.6
  '@eslint/js': 10.0.1
  '@item-enonic-types/lib-cache': 2.2.1
  '@item-enonic-types/lib-http-client': 3.2.2
  '@item-enonic-types/lib-thymeleaf': 2.1.0
  '@swc/cli': 0.7.9
  '@swc/core': 1.11.24
  '@types/jest': 30.0.0
  '@types/node': 26.1.2
  '@typescript-eslint/eslint-plugin': 8.65.0
  '@typescript-eslint/parser': 8.65.0
  dayjs: 1.11.13
  eslint: 10.8.0
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.5
  eslint-plugin-import: 2.32.0
  eslint-plugin-prettier: 5.5.6
  graphql: 16.14.2
  html-entities: 2.5.2
  jest: 30.2.0
  prettier: 3.9.6
  striptags: 3.2.0
  testcontainers: 11.11.0
  ts-jest: 29.4.6
  ts-node: 10.9.2
  typescript: 5.9.3
minimumReleaseAge: 10080
allowBuilds:
  '@swc/core': true
  cpu-features: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
