// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FormDetailsSelector = {
  /**
   * Velg alle detaljer som skal brukes på denne siden
   */
  formDetailsTargets?: Array<string> | string;
}
