// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AlertInContext {
  /**
   * Type
   */
  type?: "critical" | "information";

  /**
   * Varselmelding
   */
  text?: string;

  /**
   * Vis kun på bestemte områder eller url'er
   */
  scope:
    | {
        /**
         * Selected
         */
        _selected: "url";

        /**
         * Vis kun på bestemte URL'er
         */
        url: {
          /**
           * Vis kun på bestemte URL'er
           */
          url: Array<{
            /**
             * URL
             */
            urls: Array<string>;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "area";

        /**
         * Vis kun på bestemte områder
         */
        area: {
          /**
           * Velg område
           */
          area: Array<"sykepenger" | "dagpenger" | "minside">;
        };
      };
}
