// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AlertInContext {
  /**
   * Type
   */
  type?: "critical" | "information";

  /**
   * Varselmelding
   */
  text?: string;

  /**
   * Velg sider og innhold hvor varselet skal vises
   */
  targetContent: Array<string>;
}
