// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContactStepData = {
  /**
   * Overskrift
   */
  linksHeading?: string;

  /**
   * Undertittel
   */
  linksSubHeadline?: string;


  steps: Array<{
    /**
     * Tittel
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;


    nextStep:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Intern lenke
           */
          internal: {
            /**
             * Intern lenke
             */
            internalLink?: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Ekstern lenke
           */
          external: {
            /**
             * Ekstern URL
             */
            externalUrl?: string;
          };
        };
  }>;
};
