// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PublishingCalendarEntry = {
  /**
   * Periode
   */
  period: string;

  /**
   * Dato for publisering
   */
  date: string;

  /**
   * Lenke til relevant innhold
   */
  link?: string;
};
