// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductBlob {
  /**
   * Målgruppe
   */
  audience: "person" | "employer" | "provider" | "self_employed";

  /**
   * Områder
   */
  area: Array<"work" | "family" | "health" | "accessibility" | "pension" | "social_counselling" | "municipality" | "self_employed" | "other">;

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Innholdstype og kategorier
   */
  contentCategory:
    | {
        /**
         * Selected
         */
        _selected: "product-page";

        /**
         * Produktside
         */
        "product-page": {
          /**
           * Kategorier
           */
          taxonomy?: Array<"assistive_tools" | "followup" | "benefits" | "measures" | "service" | "rights" | "for_employers" | "for_providers" | "for_municipality" | "for_event_organizers" | "for_health_service">;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "themed-article-page";

        /**
         * Temaartikkel
         */
        "themed-article-page": {
          /**
           * Kategorier
           */
          taxonomy?: Array<"tips_job" | "help_work" | "when_sick" | "payment" | "complaint_rights" | "user_support" | "about_nav" | "membership_national_insurance" | "recruitment">;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "guide-page";

        /**
         * Guide ("Slik gjør du")
         */
        "guide-page": Record<string, unknown>;
      };

  /**
   * Velg eier
   */
  owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

  /**
   * Velg forvalter (hvis annet enn eier)
   */
  "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

  /**
   * Items goes here
   */
  dummy?: undefined;

  /**
   * Norsk bokmål
   */
  contentNo?: {
    /**
     * Produktnavn
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Velg produktside
     */
    productPage?: string;

    /**
     * Saksbehandlingstider
     */
    processing_times?: string;

    /**
     * Utbetalingsdatoer
     */
    payout_dates?: string;

    /**
     * Satser
     */
    rates?: string;
  };

  /**
   * Nynorsk
   */
  contentNn?: {
    /**
     * Produktnavn
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Velg produktside
     */
    productPage?: string;

    /**
     * Saksbehandlingstider
     */
    processing_times?: string;

    /**
     * Utbetalingsdatoer
     */
    payout_dates?: string;

    /**
     * Satser
     */
    rates?: string;
  };

  /**
   * Engelsk
   */
  contentEn?: {
    /**
     * Produktnavn
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Velg produktside
     */
    productPage?: string;

    /**
     * Saksbehandlingstider
     */
    processing_times?: string;

    /**
     * Utbetalingsdatoer
     */
    payout_dates?: string;

    /**
     * Satser
     */
    rates?: string;
  };

  /**
   * Samisk
   */
  contentSe?: {
    /**
     * Produktnavn
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Velg produktside
     */
    productPage?: string;

    /**
     * Saksbehandlingstider
     */
    processing_times?: string;

    /**
     * Utbetalingsdatoer
     */
    payout_dates?: string;

    /**
     * Satser
     */
    rates?: string;
  };

  /**
   * Andre språk
   */
  contentOther?: Array<{
    /**
     * To-bokstavers språkkode
     */
    lang: string;

    /**
     * Produktnavn
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Velg produktside
     */
    productPage?: string;

    /**
     * Saksbehandlingstider
     */
    processing_times?: string;

    /**
     * Utbetalingsdatoer
     */
    payout_dates?: string;

    /**
     * Satser
     */
    rates?: string;
  }>;
}
