apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: xp-navno-deploy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{ image }}
  envFrom:
    - secret: xp-navno-deploy
  accessPolicy:
    outbound:
      external:
        - host: {{ xpAdminHost }}
  command:
    - echo
    - $XP_USER
#    - curl
#    - --cacert
#    - /etc/pki/tls/cacert.pem
#    - -k
#    - "https://{{ xpAdminHost }}{{ xpAdminInstallServicePath }}"
#    - --user
#    - "{{ XP_USER }}:{{ XP_PASSWORD }}"
#    - -F
#    - file="chucknorris-2.2.3.jar"
