// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AlertBox = {
  /**
   * Innhold
   */
  body: string;

  /**
   * Type
   */
  type: "info" | "success" | "warning" | "error";

  /**
   * Størrelse
   */
  size?: "medium" | "small";

  /**
   * Uten bakgrunn (inline)
   */
  inline: boolean;
};
