// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FragmentCreator {
  /**
   * Velg type fragment. Obs: Du må laste inn editoren på nytt etter første lagring!
   */
  type: "part" | "layout";
}
