// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FragmentCreator {
  /**
   * Velg type fragment. Obs: Du bør laste inn editoren på nytt etter lagring av valget (F5)
   */
  type: "part" | "layout";
}
