// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TypeOfRedirect {
  /**
   * Permanent redirect (innhold flyttet til ny url)
   */
  permanentRedirect: boolean;
}
