// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TransportPage {
  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Overskrift over lenkepanelene
   */
  panelsHeading?: string;

  /**
   * Klikkbart lenkepanel
   */
  panelItems?: Array<{
    /**
     * Paneltittel
     */
    title: string;

    /**
     * Panelbeskrivelse
     */
    ingress?: string;

    /**
     * Peker til innhold
     */
    url: {
      /**
       * URL til lenke
       */
      text?: string;

      /**
       * ELLER - Velg innhold
       */
      ref?: string;
    };
  }>;

  /**
   * Fant du det du lette etter?
   */
  feedbackToggle: boolean;

  /**
   * Chatbot Frida
   */
  chatbotToggle: boolean;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i eksternt søk - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  noindex: boolean;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: string;
}
