// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContactStepPage = {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Tekst over tittel
   */
  textAboveTitle?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Ingress
   */
  html?: string;

  /**
   * Må begynne med '/start/[målgruppe dersom ikke privatperson]'
   */
  customPath: string;

  /**
   * Overskrift
   */
  linkPanelsHeading?: string;

  /**
   * Undertittel
   */
  linkPanelsSubHeading?: string;

  /**
   * Enkeltsteg
   */
  linkPanels: Array<{
    /**
     * Innhold det skal lenkes til
     */
    target: string;

    /**
     * Lenketekst (hvis tom vil tittel på innholdet vises)
     */
    text?: string;

    /**
     * Ingress
     */
    ingress?: string;
  }>;

  /**
   * Tilbakelenke
   */
  backLink: {
    /**
     * Innhold det skal lenkes til
     */
    target: string;

    /**
     * Lenketekst (hvis tom vil tittel på innholdet vises)
     */
    text?: string;
  };
};
