// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContactStepPage = {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Tekst over tittel
   */
  textAboveTitle?: string;

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Ingress
   */
  html?: string;

  /**
   * Må begynne med '/start/[målgruppe dersom ikke privatperson]'
   */
  customPath: string;

  /**
   * Overskrift
   */
  linksHeading?: string;

  /**
   * Undertittel
   */
  linksSubHeadline?: string;


  links: Array<{
    /**
     * Tittel
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;


    link:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Intern lenke
           */
          internal: {
            /**
             * Intern lenke
             */
            internalContent?: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Ekstern lenke
           */
          external: {
            /**
             * Ekstern URL
             */
            externalUrl?: string;
          };
        };
  }>;


  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Intern lenke
         */
        internal: {
          /**
           * Innhold det skal lenkes til
           */
          target: string;

          /**
           * Lenketekst (hvis tom vil tittel på innholdet vises)
           */
          text?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * Ekstern lenke
         */
        external: {
          /**
           * URL
           */
          url: string;

          /**
           * Lenketekst
           */
          text: string;
        };
      };
};
