// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContactStepPage = {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Tekst over tittel
   */
  textAboveTitle?: string;

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Ingress
   */
  html?: string;

  /**
   * Må begynne med '/start/[målgruppe dersom ikke privatperson]'
   */
  customPath: string;

  /**
   * Overskrift
   */
  linksHeading?: string;

  /**
   * Undertittel
   */
  linksSubHeadline?: string;


  steps: Array<{
    /**
     * Tittel
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;


    nextStep:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Intern lenke
           */
          internal: {
            /**
             * Intern lenke
             */
            internalContent?: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Ekstern lenke
           */
          external: {
            /**
             * Ekstern URL
             */
            externalUrl?: string;
          };
        };
  }>;
};
