// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type IndexPage = import("./index-page").IndexPage;
export type MainPage = import("./main-page").MainPage;
export type PageWithSideMenus = import("./page-with-side-menus").PageWithSideMenus;
export type ProductDetailsPage = import("./product-details-page").ProductDetailsPage;
export type SingleColPage = import("./single-col-page").SingleColPage;
export type TwoColsPage = import("./two-cols-page").TwoColsPage;

declare global {
  interface XpPageMap {
    "no.nav.navno:index-page": IndexPage;
    "no.nav.navno:main-page": MainPage;
    "no.nav.navno:page-with-side-menus": PageWithSideMenus;
    "no.nav.navno:product-details-page": ProductDetailsPage;
    "no.nav.navno:single-col-page": SingleColPage;
    "no.nav.navno:two-cols-page": TwoColsPage;
  }
}
