// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ProductCardMicro = {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Velg side
   */
  "card-list": Array<string> | string;
};
