// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageMeta {
  /**
   * Type innhold
   */
  contentType:
    | {
        /**
         * Selected
         */
        _selected: "content-page-with-sidemenus";

        /**
         * Produktside
         */
        "content-page-with-sidemenus": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Kategori
           */
          taxonomy?: Array<"insurance" | "measures" | "service" | "rights" | "assistive_tools" | "benefits" | "employee_benefits" | "refund">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Saksbehandlingstider
           */
          processing_times?: string;

          /**
           * Utbetalingsdatoer
           */
          payout_dates?: string;

          /**
           * Satser
           */
          rates?: string;

          /**
           * Velg alle detaljer som skal brukes på denne siden
           */
          formDetailsTargets?: Array<string>;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "situation-page";

        /**
         * Situasjonsside
         */
        "situation-page": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Skriv inn ønsket kort-url
           */
          customPath: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "tools-page";

        /**
         * Verktøyside
         */
        "tools-page": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Kategorier
           */
          taxonomy?: Array<"calculator" | "navigator">;

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Skriv inn ønsket kort-url
           */
          customPath: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Legg til andre språkversjoner
           */
          languages?: Array<string>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "generic-page";

        /**
         * Generisk side
         */
        "generic-page": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Skriv inn ønsket kort-url
           */
          customPath: string;

          /**
           * Legg til andre språkversjoner
           */
          languages?: Array<string>;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;

          /**
           * Oppsummering
           */
          description?: string;

          /**
           * Sidebeskrivelse for søk og sosiale medier
           */
          metaDescription?: string;

          /**
           * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
           */
          canonicalUrl?: string;

          /**
           * Skal ikke vises i søk
           */
          noindex: boolean;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "themed-article-page";

        /**
         * Temaartikkel
         */
        "themed-article-page": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Kategorier
           */
          taxonomy?: Array<"tips_job" | "help_work" | "when_sick" | "payment" | "complaint_rights" | "user_support" | "about_nav" | "membership_national_insurance" | "recruitment">;

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Skriv inn ønsket kort-url
           */
          customPath: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Saksbehandlingstider
           */
          processing_times?: string;

          /**
           * Utbetalingsdatoer
           */
          payout_dates?: string;

          /**
           * Satser
           */
          rates?: string;

          /**
           * Legg til andre språkversjoner
           */
          languages?: Array<string>;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;

          /**
           * Oppsummering
           */
          description?: string;

          /**
           * Sidebeskrivelse for søk og sosiale medier
           */
          metaDescription?: string;

          /**
           * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
           */
          canonicalUrl?: string;

          /**
           * Skal ikke vises i søk
           */
          noindex: boolean;
        };
      };
}
