// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageHeaderPartConfig {
  /**
   * Tittel på underforside
   */
  title?: string;

  /**
   * Sett bakgrunnsfarge
   */
  bgColor?: string;
}
