// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface OfficeEditorialPage {
  /**
   * Velg kontortype som denne skal vises på
   */
  type:
    | {
        /**
         * Selected
         */
        _selected: "LOKAL";

        /**
         * Lokalkontor
         */
        LOKAL: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "HMS";

        /**
         * Hjelpemiddelsentral
         */
        HMS: {
          /**
           * Velg hjelpemiddelsentral
           */
          hmsOffice: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "ALS";

        /**
         * Arbeidslivssenter
         */
        ALS: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "OPPFUTLAND";

        /**
         * NAV Utland og fellestjenester
         */
        OPPFUTLAND: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "FPY";

        /**
         * Saksbehandlingsenheter og styringsenheter (FPY)
         */
        FPY: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "YTA";

        /**
         * Saksbehandlingsenheter og styringsenheter (YTA)
         */
        YTA: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "KLAGE";

        /**
         * NAV Klageinstans
         */
        KLAGE: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "OKONOMI";

        /**
         * NAV Økonomi Stønad
         */
        OKONOMI: Record<string, unknown>;
      };

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string>;

  /**
   * Fant du det du lette etter?
   */
  feedbackToggle: boolean;

  /**
   * Chatbot Frida
   */
  chatbotToggle: boolean;

  /**
   * Oppsummering
   */
  description?: string;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i søk
   */
  noindex: boolean;

  /**
   * Ikke vis utdrag (snippets) i Google-søk
   */
  nosnippet: boolean;
}
