// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ContentDataLocaleFallback {
  /**
   * Oversettelser (listen autogenererer inntil 500 elementer)
   */
  items?: Array<{
    /**
     * Aktiver oversettelse (husk å kryss av!)
     */
    enabled: boolean;

    /**
     * Sidetittel
     */
    title: string;

    /**
     * Tittel for utlisting og sortering
     */
    sortTitle?: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Overstyr URL
     */
    externalProductUrl?: string;

    /**
     * Velg et innhold
     */
    contentId: string;
  }>;

  /**
   * Velg innholdstyper
   */
  contentTypes: Array<string>;

  /**
   * Må være en gyldig NoQL query string
   */
  contentQuery: string;
}
