// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ThemedArticleData {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Målgruppe
   */
  audience: "person" | "employer" | "provider";

  /**
   * Kategori
   */
  taxonomy?: Array<"benefits" | "followup" | "rights">;

  /**
   * Tilleggskategori
   */
  customCategory?: string;

  /**
   * Områdekategori
   */
  area?: Array<"work" | "family" | "health" | "accessibility" | "pension" | "social_counselling">;

  /**
   * Velg piktogram
   */
  illustration?: string;
}
