// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Video = {
  /**
   * Videotittel
   */
  title: string;

  /**
   * Qbrick media-id
   */
  mediaId: string;

  /**
   * Qbrick konto-id
   */
  accountId: number;

  /**
   * Bildeplakat
   */
  poster?: string;

  /**
   * Spilletid i sekunder
   */
  duration?: string;

  /**
   * Tilgjengelige språk (undertekster)
   */
  subtitles?: Array<string> | string;
};
