// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Taxonomy {
  /**
   * Kategori
   */
  taxonomy?: Array<"assistive_tools" | "benefits" | "measures" | "service" | "rights" | "for_providers">;
}
