// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FormIntermediateStepDataAction = {
  /**
   * Tittel på valget
   */
  label: string;

  /**
   * Ekstra forklaring
   */
  explanation?: string;

  /**
   * Informasjon om språk
   */
  languageDisclaimer?: string;
};
