// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface HtmlAreaPartConfig {
  /**
   * Tittel og ankerlenke
   */
  anchoring?:
    | {
        /**
         * Selected
         */
        _selected: "titleAndAnchor";

        /**
         * Bruk tittel og ankerlenke
         */
        titleAndAnchor: {
          /**
           * Tittel
           */
          header: string;

          /**
           * Anker-id
           */
          anchorId: string;

          /**
           * Ikke vis under innhold
           */
          hideFromInternalNavigation: boolean;
        };
      };

  /**
   * Innhold
   */
  html: string;

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string>;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
