// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface HtmlAreaPartConfig {
  /**
   * Innhold
   */
  html: string;

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Utvidet som standard
   */
  expandableOpenByDefault: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string>;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
