// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetails {
  /**
   * Type produktdetaljer
   */
  detailType: "rates" | "payout_dates" | "processing_times";

  /**
   * Velg tilhørende sider:
   */
  pageUsageReference: Array<string>;
}
