// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LinkToLayerConfig {
  /**
   * Velg språkversjon
   */
  locale: "no" | "nn" | "en" | "se";

  /**
   * Tekst
   */
  body: string;

  /**
   * Tooltip
   */
  tooltip?: string;

  /**
   * Innhold
   */
  target: string;

  /**
   * Åpne i ny fane
   */
  newTab: boolean;

  /**
   * Anker
   */
  anchorId?: string;
}
