// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicLinkListPartConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Lenker
   */
  list: 
  | {
      /**
       * Selected
       */
      _selected: "contentList";

      /**
       * Hent lenker fra innholdsliste
       */
      contentList: {
        /**
         * Maks antall lenker som vises
         */
        numLinks?: number;

        /**
         * Velg innholdsliste
         */
        target: string;
      }
    }
  | {
      /**
       * Selected
       */
      _selected: "linkList";

      /**
       * Sett lenker direkte
       */
      linkList: {
        /**
         * Lenke
         */
        links?: Array<
        | {
            /**
             * Selected
             */
            _selected: "internal";

            /**
             * Intern lenke
             */
            internal: {
              /**
               * Innhold det skal lenkes til
               */
              target: string;

              /**
               * Lenketekst (hvis tom vil tittel på innholdet vises)
               */
              text?: string;
            }
          }
        | {
            /**
             * Selected
             */
            _selected: "external";

            /**
             * Ekstern lenke
             */
            external: {
              /**
               * URL
               */
              url: string;

              /**
               * Lenketekst
               */
              text: string;
            }
          }
        >;
      }
    };
}
