// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicLinkListConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Lenker
   */
  list: 
  | {
      /**
       * Selected
       */
      _selected: "contentList";

      /**
       * Hent lenker fra innholdsliste
       */
      contentList: Record<string, unknown>
    }
  | {
      /**
       * Selected
       */
      _selected: "linkList";

      /**
       * Sett lenker direkte
       */
      linkList: {
        /**
         * Lenke
         */
        links?: Array<
        | {
            /**
             * Selected
             */
            _selected: "internal";

            /**
             * Intern lenke
             */
            internal: Record<string, unknown>
          }
        | {
            /**
             * Selected
             */
            _selected: "external";

            /**
             * Ekstern lenke
             */
            external: Record<string, unknown>
          }
        >;
      }
    };
}
