// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageNavigationMenu {
  /**
   * Overstyr lenketekster
   */
  anchorLinks?: Array<{
    /**
     * Anker-id
     */
    anchorId: string;

    /**
     * Lenketekst
     */
    linkText: string;
  }>;
}
