// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SearchOrder = {
  /**
   * Sett en egenvalgt sorteringsrekkefølge for dette innholdet i søkeresultater (lavere tall rangeres høyere i resultatlista). Dette gjelder kun når ingen søkeord er skrevet inn.
   */
  searchOrder?: number;
}
