// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Fasetter {
  /**
   * Fasetter
   */
  facets?: Array<{
    /**
     * Fasett
     */
    facet: string;

    /**
     * Underfasetter
     */
    underfacets?: Array<string>;
  }>;

  /**
   * Fasett (deprecated)
   */
  fasett?: string;

  /**
   * Underfasett (deprecated)
   */
  underfasett?: string;

  /**
   * -
   */
  className?: undefined;
}
