// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FrontpageContact = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Hent tekster fra delte åpningstider
   */
  sharedContactInformation?: Array<string> | string;

  /**
   * Overstyr header
   */
  chatTitle?: string;

  /**
   * Overstyr avvikstekst
   */
  chatAlertText?: string;

  /**
   * Overstyr ingress
   */
  chatIngress?: string;

  /**
   * Header
   */
  contactUsTitle: string;

  /**
   * Avvikstekst
   */
  contactUsAlertText?: string;

  /**
   * Ingress
   */
  contactUsIngress: string;

  /**
   * Lenke til kontakt-oss side
   */
  contactUsLink: string;
}
