// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageShortcutsPartConfig {
  /**
   * Tittel på seksjon
   */
  title?: string;

  /**
   * Velg snarveier
   */
  shortcuts?: Array<{
    /**
     * Tittel på snarvei
     */
    customTitle?: string;

    /**
     * Velg piktogram
     */
    customIllustration?: string;

    /**
     * Velg innhold
     */
    target: string;
  }>;

  /**
   * Overstyr bakgrunnsfarge
   */
  bgColor?: string;

  /**
   * Overstyr farge på farge på snarveiene
   */
  itemColor?: string;

  /**
   * Overstyr farge på hover-effekt på snarveiene
   */
  hoverColor?: string;
}
