// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageShortcutsPartConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Velg maks 3 snarveier
   */
  shortcutList?: Array<string>;
}
