// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PayoutDates {
  /**
   * Utbetalingsdatoer
   */
  dates: {
    /**
     * Januar
     */
    jan: number;

    /**
     * Februar
     */
    feb: number;

    /**
     * Mars
     */
    mar: number;

    /**
     * April
     */
    apr: number;

    /**
     * Mai
     */
    may: number;

    /**
     * Juni
     */
    jun: number;

    /**
     * Juli
     */
    jul: number;

    /**
     * August
     */
    aug: number;

    /**
     * September
     */
    sep: number;

    /**
     * Oktober
     */
    oct: number;

    /**
     * November
     */
    nov: number;

    /**
     * Desember
     */
    dec: number;
  };

  /**
   * Merknader
   */
  notes?: {
    /**
     * Selected
     */
    _selected: Array<"no" | "nn" | "en" | "se" | "pl">;
    
    /**
     * Norsk
     */
    no: {
      /**
       * Tekst
       */
      html: string;
    };
    
    /**
     * Nynorsk
     */
    nn: {
      /**
       * Tekst
       */
      html: string;
    };
    
    /**
     * Engelsk
     */
    en: {
      /**
       * Tekst
       */
      html: string;
    };
    
    /**
     * Samisk
     */
    se: {
      /**
       * Tekst
       */
      html: string;
    };
    
    /**
     * Polsk
     */
    pl: {
      /**
       * Tekst
       */
      html: string;
    };
  };
}
