// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetailsSelector {
  /**
   * Saksbehandlingstider
   */
  processing_times?: string;

  /**
   * Utbetalingsdatoer
   */
  payout_dates?: string;

  /**
   * Satser
   */
  rates?: string;
}
