// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CacheInvalidationDeferConfig {
  /**
   * Should defer
   */
  shouldDefer: boolean;

  /**
   * Max defer time
   */
  maxDeferTime?: number;
}
