// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface RedirectToLayer {
  /**
   * Velg en lokalisert språkversjon
   */
  locale?: "nn" | "en" | "se";
}
