// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface RedirectToLayer {
  /**
   * Dette feltet skal kun brukes dersom denne siden ikke finnes på norsk bokmål
   */
  locale?: "nn" | "en" | "se";
}
