// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface UserTestsPartConfig {
  /**
   * Velg test-gruppering
   */
  tests: string;

  /**
   * Skriv inn variant-id'er dersom kun spesifikk varianter skal kunne vises
   */
  selectedTestIds?: Array<string>;
}
