// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductCardPartConfig {
  /**
   * Velg side
   */
  targetPage?: string;

  /**
   * Overstyr ingress
   */
  ingressOverride?: string;
}
