// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PreviewOnly = {
  /**
   * Viser publisert innhold kun under nav.no/utkast/
   */
  previewOnly: boolean;
}
