// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MenuItem {
  /**
   * Show in Menu?
   */
  menuItem: boolean;

  /**
   * Override menu name
   */
  menuName?: string;

  /**
   * Open in new window?
   */
  newWindow: boolean;
}
