// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SearchConfigV2 {
  /**
   * Standard-oppsett
   */
  defaultConfig: {
    /**
     * Felt for tittel
     */
    titleKey: Array<string>;

    /**
     * Felt for ingress
     */
    ingressKey: Array<string>;

    /**
     * Felt for målgrupper
     */
    audienceKey: Array<string>;
  };

  /**
   * Oppsett for innholdstyper
   */
  groupConfig?: Array<{
    /**
     * Navn på denne gruppen
     */
    name?: string;

    /**
     * Velg innholdstyper for denne gruppen
     */
    contentTypes: Array<string>;

    /**
     * Felt for tittel
     */
    titleKey?: Array<string>;

    /**
     * Felt for ingress
     */
    ingressKey?: Array<string>;

    /**
     * Felt for målgrupper
     */
    audienceKey?: Array<string>;

    /**
     * Felter for innhold
     */
    textKey?: Array<string>;
  }>;
}
