// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductCardMicroConfig {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Velg side
   */
  "card-list": Array<string>;
}
