// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ChatbotLink = {
  /**
   * Lenke-tekst
   */
  text: string;

  /**
   * Vis lenken som
   */
  presentation: "link" | "button";
};
