// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageLoggedinCardPartConfig {
  /**
   * Velg type kort
   */
  type:
    | {
        /**
         * Selected
         */
        _selected: "meldekort";

        /**
         * Meldekort
         */
        meldekort: {

          link:
            | {
                /**
                 * Selected
                 */
                _selected: "internal";

                /**
                 * Intern lenke
                 */
                internal: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "external";

                /**
                 * Ekstern lenke
                 */
                external: Record<string, unknown>;
              };
        };
      };
}
