// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductCardMicroPartConfig {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Produkt eller livssituasjon
   */
  "card-list"?: Array<{
    /**
     * Velg side
     */
    targetPage?: string;
  }>;
}
