// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CalculatorPartConfig {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Velg kalkulator
   */
  targetCalculator?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string>;

  /**
   * Logikk
   */
  filterLogic: "or" | "and";
}
