// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicLinkPanelConfig {
  /**
   * Bakgrunnsbilde (valgfritt)
   */
  background?: string;

  /**
   * Varianter
   */
  variant?: 
  | {
      /**
       * Selected
       */
      _selected: "vertical";

      /**
       * Standard vertikalt layout
       */
      vertical: Record<string, unknown>
    }
  | {
      /**
       * Selected
       */
      _selected: "verticalWithBgColor";

      /**
       * Vertikalt med stort ikon og bakgrunnsfarge
       */
      verticalWithBgColor: {
        /**
         * Bakgrunnsfarge
         */
        iconBg?: {

        };

        /**
         * Posisjon på ikonet
         */
        iconJustify: "flex-start" | "center" | "flex-end";
      }
    };
}
