// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicLinkPanelPartConfig {

  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Intern lenke
         */
        internal: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * Ekstern lenke
         */
        external: Record<string, unknown>;
      };

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Vertikalt layout
   */
  vertical: boolean;

  /**
   * Ikon (valgfritt)
   */
  icon?: string;

  /**
   * Bakgrunn (valgfritt)
   */
  background?: string;
}
