// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FeedbackToggle {
  /**
   * Fant du det du lette etter? - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  feedbackToggle: boolean;
}
