// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AreaNavigation {
  /**
   * Velg områder
   */
  areasRefs?: Array<string>;

  /**
   * Velg underforsider
   */
  frontPageNestedRefs?: Array<string>;

  /**
   * Velg situasjonssider
   */
  situationsRefs?: Array<string>;

  /**
   * Velg utgående navigasjonlenker
   */
  navigationRefs?: Array<string>;
}
