// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AlertInContext = {
  /**
   * Type
   */
  type?: "critical" | "information";

  /**
   * Varselmelding
   */
  text: string;

  /**
   * Velg innhold
   */
  target:
    | {
        /**
         * Selected
         */
        _selected: "formDetails";

        /**
         * Skjemadetaljer
         */
        formDetails: {
          /**
           * Velg hvilke skjemadetaljer som varselet skal vises på
           */
          targetContent: Array<string> | string;
        };
      };
};
