// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SectionWithHeaderConfig {
  /**
   * Tittel
   */
  title: string;

  /**
   * Anker-id
   */
  anchorId: string;

  /**
   * Ikon
   */
  icon?: {

  };

  /**
   * Bakgrunnsfarge
   */
  bgColor?: {

  };

  /**
   * Omriss
   */
  border?: {
    /**
     * Avrundede hjørner
     */
    rounded: boolean;

    /**
     * Tykkelse (px)
     */
    width?: number;
  };
}
