// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SectionWithHeaderConfig {
  /**
   * Tittel
   */
  title: string;

  /**
   * Anker-id
   */
  anchorId: string;

  /**
   * Justering
   */
  justify: "left" | "center" | "right";

  /**
   * Typografi
   */
  typo:
    | {
        /**
         * Selected
         */
        _selected: "default";

        /**
         * Standard
         */
        default: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "custom";

        /**
         * Tilpasset
         */
        custom: {
          /**
           * Velg typografi-stil
           */
          typo: "sidetittel" | "innholdstittel" | "systemtittel" | "undertittel" | "element";
        };
      };

  /**
   * Ikon
   */
  icon?: string;

  /**
   * Bakgrunnsfarge (6-siffer hex-kode, eks. #2f0055)
   */
  backgroundColor?: string;

  /**
   * Fremhevet
   */
  highlight: boolean;
}
