// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type HtmlArea = {
  /**
   * Innhold
   */
  html: string;

  /**
   * Type innhold
   */
  type?: "documentation_requirements" | "processing_times" | "rates";

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string> | string;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
