// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MegamenuItem = {
  /**
   * Velg innhold
   */
  target?: string;

  /**
   * Nivå 4 - Vis hengelås
   */
  displayLock: boolean;

  /**
   * Ekspander underelementer
   */
  flatten: boolean;

  /**
   * Spesiell ID
   */
  specialID?: string;
};
