// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type UnpublishExpiredContent = {
  /**
   * Node path
   */
  path: string;

  /**
   * Node id
   */
  id: string;

  /**
   * Repo id
   */
  repoId?: string;
};
