// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type CmsContent = import("./cmsContent").CmsContent
export type CmsMenu = import("./cmsMenu").CmsMenu
export type CmsStatus = import("./cmsStatus").CmsStatus
export type Fasetter = import("./fasetter").Fasetter
export type MenuItem = import("./menu-item").MenuItem
export type OldContentType = import("./oldContentType").OldContentType
export type PreviewOnly = import("./previewOnly").PreviewOnly
export type RedirectToLayer = import("./redirectToLayer").RedirectToLayer
export type SearchOrder = import("./searchOrder").SearchOrder
export type VirtualParent = import("./virtualParent").VirtualParent

declare global {
  interface XpXData {
    "no-nav-navno"?: {
      cmsContent?: CmsContent;
      cmsMenu?: CmsMenu;
      cmsStatus?: CmsStatus;
      fasetter?: Fasetter;
      "menu-item"?: MenuItem;
      oldContentType?: OldContentType;
      previewOnly?: PreviewOnly;
      redirectToLayer?: RedirectToLayer;
      searchOrder?: SearchOrder;
      virtualParent?: VirtualParent;
    }
  }
}
