// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface GuideData {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Områdekategori
   */
  area?: Array<"work" | "family" | "health" | "accessibility" | "pension" | "social_counselling">;

  /**
   * Velg illustrasjon
   */
  illustration?: string;
}
