// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Notification {
  /**
   * Tittel (overstyrer sidetittel fra valgt innhold)
   */
  title?: string;

  /**
   * Vis beskrivelse/ingress
   */
  showDescription: boolean;

  /**
   * Vis oppdateringstidspunkt
   */
  showUpdated: boolean;

  /**
   * Innhold det henvises til
   */
  target: string;

  /**
   * Hvis du skal ersatte et globalt varsel, velg hvilket
   */
  notificationToReplaceId?: string;

  /**
   * Ikon-type (deprecated, overstyres dersom ikon er valgt ovenfor)
   */
  type?: "warning" | "info";
}
