// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FragmentCreator = {
  /**
   * Velg type fragment og lagre
   */
  type: "part" | "layout";
}
