// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface EmployerSituationData {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Målgruppe
   */
  audience: "person" | "employer" | "provider";

  /**
   * Områdekategori
   */
  area?: Array<undefined>;

  /**
   * Velg piktogram
   */
  illustration?: string;

  /**
   * Videresend alle besøk til annen url:
   */
  externalProductUrl?: string;
}
