// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicHeaderConfig {
  /**
   * Tittel
   */
  title: string;

  /**
   * Anker-id
   */
  anchorId?: string;

  /**
   * Heading tag
   */
  titleTag: "h2" | "h3" | "h4" | "h5" | "h6";
}
