// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SectionWithHeaderV2 = {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Anker-id
   */
  anchorId?: string;

  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Ikke vis i intern innholdsmeny
   */
  hideFromInternalNavigation: boolean;

  /**
   * Ikon
   */
  icon?: {
    /**
     * Velg ikon
     */
    icon?: string;
  };
}
