// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Dynamic3ColConfig {
  /**
   * Bredde-fordeling (xx-xx-xx)
   */
  distribution?: string;
}
