// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PublishingCalendar {
  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i eksternt søk - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  noindex: boolean;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: string;
}
