kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-blobs
  namespace: girons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-data
  namespace: girons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-snapshots
  namespace: girons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: giropops-deploy
  namespace: girons
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi