// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MainPanels {
  /**
   * Oppgi antall tavler/bokser på seksjonssiden
   */
  nrTableEntries?: number;

  /**
   * Velg innhold
   */
  tableContents?: Array<string>;
}
