// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageLoggedinSectionConfig {
  /**
   * Tekst
   */
  header: string;

  /**
   * Min side lenke
   */
  mypage?: {

    link:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Intern lenke
           */
          internal: Record<string, unknown>;
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Ekstern lenke
           */
          external: Record<string, unknown>;
        };
  };
}
