// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface TestRecruiterPartConfig {
  /**
   * Velg test-gruppering
   */
  tests: string;

  /**
   * Plukk ut enkelte test(er)
   */
  selectedTestIds?: Array<string>;
}
