// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LinkPanelsConfig {
  /**
   * Overskrift over lenkepanelene
   */
  panelsHeading?: string;

  /**
   * Klikkbart lenkepanel
   */
  panelItems?: Array<{
    /**
     * Paneltittel
     */
    title: string;

    /**
     * Panelbeskrivelse
     */
    ingress?: string;

    /**
     * Heldekkende panel
     */
    spanning: boolean;

    /**
     * Peker til innhold
     */
    url: {
      /**
       * URL til lenke
       */
      text?: string;

      /**
       * ELLER - Velg innhold
       */
      ref?: string;
    };
  }>;
}
