// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CmsStatus {
  /**
   * Status
   */
  status?: "draft" | "snapshot" | "approved" | "archived";
}
