// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PublishingCalendar = {
  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Ikke vis "tilfeldige "
   */
  noindex: boolean;

  /**
   * Ikke vis "tilfeldige" utdrag (snippets) i Google-søk
   */
  nosnippet: boolean;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: Array<string> | string;
};
