// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ButtonPartConfig {

  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Intern lenke
         */
        internal: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * Ekstern lenke
         */
        external: Record<string, unknown>;
      };

  /**
   * Type
   */
  type: "standard" | "hoved" | "fare" | "flat";

  /**
   * Størrelse
   */
  size: "normal" | "kompakt" | "mini";

  /**
   * Full bredde
   */
  fullwidth: boolean;

  /**
   * Ikon (valgfritt)
   */
  icon?: string;
}
