// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ButtonConfig {
  /**
   * Type
   */
  type: "standard" | "hoved" | "fare" | "flat";

  /**
   * Størrelse
   */
  size: "normal" | "kompakt" | "mini";

  /**
   * Full bredde
   */
  fullwidth: boolean;
}
