// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PressLandingPage {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Informasjon om pressevakt
   */
  pressCall?: string;

  /**
   * Hvor mange nyheter i listen er tillatt
   */
  maxNewsCount?: string;

  /**
   * Velg innhold
   */
  pressNews: string;

  /**
   * Url til flere nyheter
   */
  moreNewsUrl?: string;

  /**
   * Hvor mange snarveier i listen er tillatt
   */
  maxShortcutsCount?: string;

  /**
   * Velg innhold
   */
  shortcuts: string;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath: string;

  /**
   * Målgruppe
   */
  audience:
    | {
        /**
         * Selected
         */
        _selected: "person";

        /**
         * Privatperson
         */
        person: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "employer";

        /**
         * Arbeidsgiver
         */
        employer: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "provider";

        /**
         * Samarbeidspartner
         */
        provider: {
          /**
           * Underkategori
           */
          provider_audience: "doctor" | "other";
        };
      };

  /**
   * Velg eier
   */
  owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

  /**
   * Velg forvalter
   */
  "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string>;
}
