// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Video {
  /**
   * Videotittel
   */
  title: string;

  /**
   * Media id
   */
  mediaId: string;

  /**
   * Konto-id
   */
  accountId: number;

  /**
   * Bildeplakat
   */
  poster?: string;

  /**
   * Spilletid i sekunder
   */
  duration?: string;

  /**
   * Tilgjengelige språk (undertekster)
   */
  subtitles?: Array<string>;
}
