// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface HeaderWithAnchorConfig {
  /**
   * Tekst
   */
  body: string;

  /**
   * Anker-id
   */
  id: string;

  /**
   * Header tag
   */
  tag: "h3" | "h4";

  /**
   * (Deprecated - Bruk "Tekst" feltet)
   */
  text?: string;
}
