// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FiltersMenuPartConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Filter-kategori
   */
  categories?: Array<{
    /**
     * Kategori-navn
     */
    categoryName?: string;

    /**
     * Filter
     */
    filters: Array<{
      /**
       * Filter-navn
       */
      filterName: string;
    }>;
  }>;

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;
}
