// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PageWithSideMenus = {
  /**
   * Vis intern-navigasjon
   */
  showInternalNav: boolean;

  /**
   * Overstyr lenketekster
   */
  anchorLinks?: Array<{
    /**
     * Anker-id
     */
    anchorId: string;

    /**
     * Lenketekst
     */
    linkText: string;
  }>;

  /**
   * Vis produktnavnet i 'Det finnes også informasjon om...'
   */
  showProductName: boolean;
}
