// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetailsConfig {
  /**
   * Saksbehandlingstider
   */
  processing_times?: string;

  /**
   * Visningsinnstillinger
   */
  processingTimesVisibility?: "all" | "application" | "complaint";

  /**
   * Utbetalingsdatoer
   */
  payout_dates?: string;

  /**
   * Satser
   */
  rates?: string;
}
