// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Video = {
  /**
   * Velg video-innhold
   */
  targetContent: string;

  /**
   * Overstyr språk for undertekster
   */
  language?: string;

  /**
   * (Ikke i bruk)
   */
  title?: string;

  /**
   * (Ikke i bruk)
   */
  video?: string;
};
