// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CmsContent {
  /**
   * Content key
   */
  contentKey?: string;

  /**
   * Category key
   */
  categoryKey?: string;

  /**
   * Content Home
   */
  contentHome?: Array<string>;
}
