// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicReadMorePanelConfig {
  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Innhold
   */
  content?: string;

  /**
   * Border
   */
  border: "true" | "false";

  /**
   * Margin på containeren
   */
  margin?: string;
}
