// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type UxsignalsWidget = {
  /**
   * Study ID (feks 'panel-12ab123456'):
   */
  embedCode: string;
};
