// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type GlobalValueWithMath = {
  /**
   * Velg verdier
   */
  keys?: Array<string> | string;

  /**
   * Skriv inn et matematisk uttrykk
   */
  expression?: string;

  /**
   * Avrunding
   */
  decimals: number;

  /**
   * -
   */
  variables?: ;
}
