// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageMetaObject {
  /**
   * Type innhold
   */
  contentType:
    | {
        /**
         * Selected
         */
        _selected: "no.nav.navno:content-page-with-sidemenus";

        /**
         * Produktside
         */
        "no.nav.navno:content-page-with-sidemenus": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Kategori
           */
          taxonomy?: Array<"insurance" | "measures" | "service" | "rights" | "assistive_tools" | "benefits" | "employee_benefits" | "refund">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Saksbehandlingstider
           */
          processing_times?: string;

          /**
           * Utbetalingsdatoer
           */
          payout_dates?: string;

          /**
           * Satser
           */
          rates?: string;

          /**
           * Velg alle detaljer som skal brukes på denne siden
           */
          formDetailsTargets?: Array<string>;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "situation-page";

        /**
         * Situasjonsside
         */
        "situation-page": {
          /**
           * Målgruppe
           */
          audience:
            | {
                /**
                 * Selected
                 */
                _selected: "person";

                /**
                 * Privatperson
                 */
                person: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "employer";

                /**
                 * Arbeidsgiver
                 */
                employer: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "provider";

                /**
                 * Samarbeidspartner
                 */
                provider: Record<string, unknown>;
              }
            | {
                /**
                 * Selected
                 */
                _selected: "other";

                /**
                 * Annet
                 */
                other: Record<string, unknown>;
              };

          /**
           * Områdekategori
           */
          area: Array<"health" | "other" | "work" | "family" | "accessibility" | "pension" | "social_counselling" | "inclusion" | "downsizing" | "recruitment">;

          /**
           * Velg piktogram
           */
          illustration: string;

          /**
           * Videresend alle besøk til annen url:
           */
          externalProductUrl?: string;

          /**
           * Skriv inn ønsket kort-url
           */
          customPath: string;

          /**
           * Velg eier
           */
          owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

          /**
           * Velg forvalter
           */
          "managed-by"?: Array<"po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver" | "digisos">;

          /**
           * Fant du det du lette etter?
           */
          feedbackToggle: boolean;

          /**
           * Chatbot Frida
           */
          chatbotToggle: boolean;
        };
      };
}
