// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FormDetails = {
  /**
   * Velg skjemadetalj
   */
  targetFormDetails: string;

  /**
   * Vis tittel
   */
  showTitle: boolean;

  /**
   * Vis ingress
   */
  showIngress: boolean;

  /**
   * Vis inngang til søknad
   */
  showApplications: boolean;

  /**
   * Vis inngang til ettersendelse
   */
  showAddendums: boolean;
};
