// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ButtonBlueConfig {
  /**
   * Url
   */
  url?: string;

  /**
   * Tekst
   */
  text: string;

  /**
   * Innhold
   */
  content?: string;
}
