// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicFlexColsConfig {
  /**
   * Antall kolonner ved full skjermbredde
   */
  numCols?: number;

  /**
   * Justering
   */
  justifyContent?: "flex-start" | "center" | "flex-end";
}
