// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type HeaderWithParent = {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Tekst over tittel
   */
  textAboveTitle?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Velg piktogram
   */
  illustration: string;
};
