// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FrontpagePersonShortcuts = {
  /**
   * Tittel på seksjon
   */
  title?: string;

  /**
   * Velg snarveier
   */
  shortcuts?: Array<{
    /**
     * Tittel på snarvei
     */
    customTitle?: string;

    /**
     * Velg innhold
     */
    target: string;
  }>;
};
