// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ContentListConfig {
  /**
   * Maks antall lenker som vises
   */
  numLinks?: number;

  /**
   * Velg innholdsliste
   */
  target: string;
}
