// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageList {
  /**
   * Orginaltittel
   */
  originaltitle?: string;

  /**
   * Skjul dato på artikkellisten
   */
  hide_date: boolean;

  /**
   * Skjul dato på artiklene i artikkellisten
   */
  hideSectionContentsDate: boolean;

  /**
   * Sorter artikkellisten etter publiseringsdato
   */
  orderSectionContentsByPublished: boolean;

  /**
   * Contents
   */
  sectionContents?: Array<string>;

  /**
   * Innhold i høyremenyen
   */
  menuListItems?: {
    /**
     * Selected
     */
    _selected: Array<"shortcuts">;
    
    /**
     * Snarveier
     */
    shortcuts: {
      /**
       * Snarveier
       */
      link?: Array<string>;
    };
  };

  /**
   * Meta tagger
   */
  metaTags?: Array<string>;
}
