// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MiscSettings {
  /**
   * Vis underpunkter (h3-overskrifter) i innholdsmenyen
   */
  showSubMenu: boolean;
}
