// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PrepublishCacheWipeConfig {
  /**
   * Node path
   */
  path: string;

  /**
   * Node id
   */
  id: string;

  /**
   * Event type
   */
  eventType: string;

  /**
   * Event timestamp
   */
  timestamp: number;
}
