// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ReadMore = {
  /**
   * Tittelen på les-mer-knapp
   */
  title: string;

  /**
   * Innhold
   */
  html: string;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
};
