// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LanguagesLegacyConfig {
  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string>;
}
