// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ToolsPage {
  /**
   * Kategori
   */
  taxonomy?: Array<"benefits" | "followup" | "rights">;

  /**
   * Skriv inn ønsket url
   */
  customPath?: string;
}
