// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ToolsPage {
  /**
   * Skriv inn ønsket url
   */
  customPath?: string;

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string>;
}
