// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetailsPartConfig {
  /**
   * Velg type produktdetalj
   */
  detailType: "processing_times" | "payout_dates" | "rates";

  /**
   * Tilpass visning
   */
  options:
    | {
        /**
         * Selected
         */
        _selected: "all";

        /**
         * Vis alle produktdetaljer
         */
        all: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "filters";

        /**
         * Filtrer visning
         */
        filters: {
          /**
           * Vis saksbehandlingstider for søknader
           */
          processing_times_applications: boolean;

          /**
           * Vis saksbehandlingstider for klage
           */
          processing_times_complaint: boolean;
        };
      };

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string>;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
