// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductDetailsPartConfig {
  /**
   * Velg type produktdetalj
   */
  detailType: "processing_times" | "payout_dates" | "rates";

  /**
   * For visning av saksbehandlingstider
   */
  processingTimesVisibility: "all" | "application" | "complaint";

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg filtre
   */
  filters?: Array<string>;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
