// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface UserTests {
  /**
   * Tittel
   */
  title: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Cookie-id
   */
  cookieId: string;

  /**
   * Start-tidspunkt
   */
  startTime?: string;

  /**
   * Slutt-tidspunkt
   */
  endTime?: string;

  /**
   * Test-varianter
   */
  variants: Array<{
    /**
     * Id for denne varianten
     */
    id: string;

    /**
     * Prosentandel av brukere som skal få denne varianten
     */
    percentage?: number;

    /**
     * Url til denne test-varianten
     */
    url: string;

    /**
     * Lenketekst
     */
    linkText: string;

    /**
     * Tilpasset tittel
     */
    title?: string;

    /**
     * Tilpasset ingress
     */
    ingress?: string;
  }>;
}
