// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MainArticle {
  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  originaltitle?: string;

  /**
   * Brødtekst
   */
  text: string;

  /**
   * Innholdstype
   */
  contentType: "news" | "pressRelease" | "lastingContent";

  /**
   * Sett inn innholdsfortegnelse
   */
  hasTableOfContents?: "none" | "h3";

  /**
   * Faktaboksen vises under brødteksten
   */
  fact?: string;

  /**
   * Bilde med beskrivelse
   */
  picture?: {
    /**
     * Bilde
     */
    target: string;

    /**
     * Velg bildestørrelse
     */
    size?: "100" | "70" | "40";

    /**
     * Bildetekst
     */
    caption: string;

    /**
     * Alternativ tekst
     */
    altText: string;
  };

  /**
   * Del på sosiale medier
   */
  social?: Array<"twitter" | "facebook" | "linkedin">;
}
