// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface PageWithSideMenusConfig {
  /**
   * Vis denne menyen
   */
  leftMenuToggle: boolean;

  /**
   * Vis intern-navigasjon
   */
  showInternalNav: boolean;

  /**
   * Sticky-meny
   */
  leftMenuSticky: boolean;

  /**
   * Tittel
   */
  leftMenuHeader?: string;

  /**
   * Vis denne menyen
   */
  rightMenuToggle: boolean;

  /**
   * Sticky-meny
   */
  rightMenuSticky: boolean;
}
