// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AnimatedIcons = {
  /**
   * Velg ikoner
   */
  icons: Array<{
    /**
     * Velg ikon
     */
    icon?: string;
  }>;
}
