// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type GlobalValue = {
  /**
   * Velg verdi
   */
  key: string;

  /**
   * Desimaler
   */
  decimals?: number;

  /**
   * -
   */
  value?: ;
}
