// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SituationFlexCols = {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Anker-id
   */
  anchorId?: string;

  /**
   * Ikke vis under innhold
   */
  hideFromInternalNavigation: boolean;

  /**
   * Toggle "kopier lenke" knapp
   */
  toggleCopyButton: boolean;

  /**
   * Innstilling for varehyller
   */
  shelf?:
    | {
        /**
         * Selected
         */
        _selected: "products";

        /**
         * Produkter
         */
        products: {
          /**
           * Prioritering
           */
          priority?: "primary" | "secondary" | "tertiary";
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "providers";

        /**
         * Samarbeidspartner
         */
        providers: Record<string, unknown>;
      };

  /**
   * Antall kolonner ved full skjermbredde
   */
  numCols?: number;

  /**
   * Justering
   */
  justifyContent?: "flex-start" | "center" | "flex-end";

  /**
   * Bakgrunnsfarge
   */
  bgColor?: {
    /**
     * Velg farge
     */
    color: string;
  };
}
