// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface VarselBoksConfig {
  /**
   * Teksten som skal legges inn
   */
  varselBoks: string;
}
