// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ExpandableConfig {
  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Utvidet som standard
   */
  expandableOpenByDefault: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;
}
