// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LocalizedContentDataFallback {
  /**
   * Velg innholdstyper
   */
  contentTypes: Array<string>;

  /**
   * Oversettelser for ikke-lokalisert innhold
   */
  items?: Array<{
    /**
     * Sidetittel
     */
    title: string;

    /**
     * Tittel for utlisting og sortering
     */
    sortTitle?: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Overstyr URL
     */
    externalProductUrl?: string;

    /**
     * Velg et ikke-lokalisert innhold
     */
    contentId: string;

    /**
     * Aktiver oversettelse
     */
    enabled: boolean;
  }>;
}
