// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface LocalizedContentDataFallback {
  /**
   * Velg innholdstyper
   */
  contentTypes: Array<string>;

  /**
   * Oversettelser for ikke-lokalisert innhold
   */
  items?: Array<{
    /**
     * Velg et ikke-lokalisert innhold
     */
    contentId: string;

    /**
     * Aktiver oversettelse
     */
    enabled: boolean;

    /**
     * Tittel
     */
    title: string;

    /**
     * Ingress
     */
    ingress: string;

    /**
     * Overstyr URL
     */
    externalProductUrl?: string;
  }>;
}
