// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface SearchOrder {
  /**
   * Høyere tall vil prioriteres høyere i søkeresultatet. Dette gjelder kun når ingen søkeord er skrevet inn.
   */
  searchOrder?: number;
}
