// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type FormDetails = {
  /**
   * Skjemanummer
   */
  formNumbers?: Array<string> | string;

  /**
   * Tittel
   */
  title: string;

  /**
   * Tittel for søk
   */
  longTitle?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Informasjon om språk
   */
  languageDisclaimer?: string;

  /**
   * Målgruppe
   */
  audience: {
    /**
     * Selected
     */
    _selected: Array<"person" | "employer" | "provider" | "other">;
    
    /**
     * Privatperson
     */
    person: Record<string, unknown>;
    
    /**
     * Arbeidsgiver
     */
    employer: Record<string, unknown>;
    
    /**
     * Samarbeidspartner
     */
    provider: {
      /**
       * Velg underkategorier
       */
      provider_audience: Array<"doctor" | "municipality_employed" | "optician" | "administrator" | "measures_organizer" | "aid_supplier" | "other"> | "doctor" | "municipality_employed" | "optician" | "administrator" | "measures_organizer" | "aid_supplier" | "other";
    };
    
    /**
     * Annet
     */
    other: Record<string, unknown>;
  };

  /**
   * Variasjoner
   */
  formType: Array<
    | {
        /**
         * Selected
         */
        _selected: "application";

        /**
         * Søknad / skjema
         */
        application: {

          variations?: Array<{
            /**
             * Knappetekst
             */
            label: string;

            /**
             * Lenke til skjema
             */
            link:
              | {
                  /**
                   * Selected
                   */
                  _selected: "internal";

                  /**
                   * Intern lenke til skjema/mellomsteg
                   */
                  internal: {
                    /**
                     * Velg skjema eller mellomsteg
                     */
                    target: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "external";

                  /**
                   * Ekstern lenke til skjema
                   */
                  external: {
                    /**
                     * Skjemanummer
                     */
                    formNumber?: string;

                    /**
                     * URL
                     */
                    url: string;
                  };
                };
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "complaint";

        /**
         * Klage- og ankevariasjoner
         */
        complaint: {

          variations?: Array<{
            /**
             * Knappetekst
             */
            label: string;

            /**
             * Lenke til skjema
             */
            link:
              | {
                  /**
                   * Selected
                   */
                  _selected: "internal";

                  /**
                   * Intern lenke til skjema/mellomsteg
                   */
                  internal: {
                    /**
                     * Velg skjema eller mellomsteg
                     */
                    target: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "external";

                  /**
                   * Ekstern lenke til skjema
                   */
                  external: {
                    /**
                     * Skjemanummer
                     */
                    formNumber?: string;

                    /**
                     * URL
                     */
                    url: string;
                  };
                };

            /**
             * Klage- eller anketype
             */
            type: "complaint" | "appeal";
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "addendum";

        /**
         * Ettersendelse
         */
        addendum: {

          variations?: Array<{
            /**
             * Knappetekst
             */
            label: string;

            /**
             * Lenke til skjema
             */
            link:
              | {
                  /**
                   * Selected
                   */
                  _selected: "internal";

                  /**
                   * Intern lenke til skjema/mellomsteg
                   */
                  internal: {
                    /**
                     * Velg skjema eller mellomsteg
                     */
                    target: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "external";

                  /**
                   * Ekstern lenke til skjema
                   */
                  external: {
                    /**
                     * Skjemanummer
                     */
                    formNumber?: string;

                    /**
                     * URL
                     */
                    url: string;
                  };
                };
          }>;
        };
      }
  >;
};
