// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContactOption = {
  /**
   * Kontakt-oss kanaler
   */
  contactOptions:
    | {
        /**
         * Selected
         */
        _selected: "chat";

        /**
         * Chat
         */
        chat: {
          /**
           * Velg chat med oss
           */
          sharedContactInformation?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;

          /**
           * (tomt felt, skal ikke brukes)
           */
          title?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "write";

        /**
         * Skriv til oss
         */
        write: {
          /**
           * Velg skriv til oss
           */
          sharedContactInformation?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;

          /**
           * (tomt felt, skal ikke brukes)
           */
          url?: string;

          /**
           * (tomt felt, skal ikke brukes)
           */
          title?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "call";

        /**
         * Ring oss
         */
        call: {
          /**
           * Velg telefonnummer
           */
          sharedContactInformation?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;

          /**
           * (tomt felt, skal ikke brukes)
           */
          phoneNumber?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "navoffice";

        /**
         * Finn ditt NAV-kontor
         */
        navoffice: {
          /**
           * Overstyr tittel
           */
          title?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "aidcentral";

        /**
         * Finn din hjelpemiddelsentral
         */
        aidcentral: {
          /**
           * Overstyr tittel
           */
          title?: string;

          /**
           * Overstyr ingress
           */
          ingress?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "custom";

        /**
         * Egentilpasset
         */
        custom: {
          /**
           * Tittel
           */
          title: string;

          /**
           * Icon
           */
          icon: "facebook" | "linkedin";

          /**
           * Url
           */
          url: string;

          /**
           * Ingress
           */
          ingress?: string;
        };
      };

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
