// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type RelatedSituations = {
  /**
   * Overstyr tittel
   */
  title?: string;

  /**
   * Overstyr introduksjon (1-2 linjer)
   */
  description?: string;
};
