// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageContactPartConfig {
  /**
   * Header
   */
  chatTitle: string;

  /**
   * Ingress
   */
  chatIngress: string;

  /**
   * Header
   */
  contactUsTitle: string;

  /**
   * Ingress
   */
  contactUsIngress: string;

  /**
   * Lenke til kontakt-oss side
   */
  contactUsLink: string;
}
