// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type CalculatorTargetSelector = {
  /**
   * Velg kalkulator
   */
  targetCalculator?: string;
};
