// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type RedirectToLayer = {
  /**
   * Obs: språkversjonen må være lokalisert
   */
  locale?: "no" | "nn" | "en" | "se";
};
