// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface CaseProcessingTime {
  /**
   * Sett antall
   */
  number: number;

  /**
   * Velg tidsenhet
   */
  unit: "days" | "weeks" | "months";
}
