// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type LenkeFiler = {
  /**
   * Felles lenketekst
   */
  text: string;

  /**
   * Legg ved filer
   */
  files: Array<string> | string;
};
