kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xp-blobs
  namespace: xp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xp-data
  namespace: xp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xp-snapshots
  namespace: xp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xp-deploy
  namespace: xp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi