// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type DynamicHeader = {
  /**
   * Tittel
   */
  title: string;

  /**
   * Anker-id
   */
  anchorId?: string;

  /**
   * Heading tag
   */
  titleTag: "h3" | "h4";

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
};
