// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FormDetailsSelector {
  /**
   * Velg alle detaljer som skal brukes
   */
  formDetailsTargets?: Array<string>;
}
