// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface ProductData {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Kategori
   */
  taxonomy?: Array<"benefits" | "followup" | "rights">;

  /**
   * Områdekategori
   */
  area?: Array<"work" | "family" | "health" | "accessibility" | "pension" | "social_counselling">;

  /**
   * Velg illustrasjon
   */
  illustration?: string;

  /**
   * Videresend alle besøk til annen url:
   */
  externalProductUrl?: string;
}
