// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type AreapageSituations = import("./areapage-situations").AreapageSituations;
export type Dynamic1Col = import("./dynamic-1-col").Dynamic1Col;
export type Dynamic2Col = import("./dynamic-2-col").Dynamic2Col;
export type Dynamic3Col = import("./dynamic-3-col").Dynamic3Col;
export type DynamicFlexCols = import("./dynamic-flex-cols").DynamicFlexCols;
export type FrontpageLoggedinSection = import("./frontpage-loggedin-section").FrontpageLoggedinSection;
export type Main1Col = import("./main-1-col").Main1Col;
export type Main = import("./main").Main;
export type ProductFlexCols = import("./product-flex-cols").ProductFlexCols;
export type SectionWithHeader = import("./section-with-header").SectionWithHeader;
export type SituationFlexCols = import("./situation-flex-cols").SituationFlexCols;

declare global {
  interface XpLayoutMap {
    "no.nav.navno:areapage-situations": AreapageSituations;
    "no.nav.navno:dynamic-1-col": Dynamic1Col;
    "no.nav.navno:dynamic-2-col": Dynamic2Col;
    "no.nav.navno:dynamic-3-col": Dynamic3Col;
    "no.nav.navno:dynamic-flex-cols": DynamicFlexCols;
    "no.nav.navno:frontpage-loggedin-section": FrontpageLoggedinSection;
    "no.nav.navno:main-1-col": Main1Col;
    "no.nav.navno:main": Main;
    "no.nav.navno:product-flex-cols": ProductFlexCols;
    "no.nav.navno:section-with-header": SectionWithHeader;
    "no.nav.navno:situation-flex-cols": SituationFlexCols;
  }
}
