// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface InternalLink {
  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Link
   */
  target?: string;

  /**
   * Redirect alle url'er under denne til valgt link (unntatt url'er med publisert innhold)
   */
  redirectSubpaths: boolean;

  /**
   * Permanent redirect (innhold flyttet til ny url)
   */
  permanentRedirect: boolean;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: string;
}
