// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface MegamenuItem {
  /**
   * Velg innhold
   */
  target?: Array<string>;

  /**
   * Nivå 4 - Vis hengelås
   */
  displayLock: boolean;
}
