// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Trekkspill = {
  /**
   * Trekkspill
   */
  trekkspill: Array<{
    /**
     * Tittel
     */
    title: string;

    /**
     * Ankerid
     */
    anchorId?: string;

    /**
     * Innhold
     */
    html: string;
  }>;
};
