// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface BreakingNews {
  /**
   * Synlighet
   */
  severity: "1" | "2" | "3";

  /**
   * Innhold det skal henvises til
   */
  target: string;

  /**
   * Tittel (overstyrer sidetittel fra valgt innhold)
   */
  title?: string;

  /**
   * Beskrivelse (overstyrer ingress fra valgt innhold)
   */
  description?: string;

  /**
   * Oppdatert tidspunkt
   */
  timestamp?: string;
}
