// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Melding {
  /**
   * Type
   */
  type?: "prodstatus" | "info";

  /**
   * Ingress
   */
  ingress?: string;

  /**
   * Brødtekst melding
   */
  text?: string;

  /**
   * Visning
   */
  urlscope:
    | {
        /**
         * Selected
         */
        _selected: "global";

        /**
         * Vises på alle sider
         */
        global: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "scoped";

        /**
         * Vises kun på bestemte URL'er
         */
        scoped: {
          /**
           * URL
           */
          urls?: Array<string>;
        };
      };
}
