// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ProductCardMicro = {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Valgt side
   */
  "card-list": Array<{
    /**
     * Velg side
     */
    targetPage?: string;
  }>;
}
