// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FrontpageSurveyPanelPartConfig {
  /**
   * Overskrift
   */
  header?: string;

  /**
   * Beskrivelse
   */
  description?: string;

  /**
   * Ikon
   */
  icon?: {
    /**
     * Velg ikon
     */
    icon?: string;

    /**
     * Størrelse (%)
     */
    size?: number;
  };

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
