// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FormIntermediateStepData {
  /**
   * Redaksjonelt innhold ovenfor valgene
   */
  editorial?: string;

  /**
   * Enkeltsteg
   */
  steps: Array<{
    /**
     * Tittel på valget
     */
    label: string;

    /**
     * Ekstra forklaring
     */
    explanation?: string;

    /**
     * Hvor blir brukeren sendt etter dette valget
     */
    nextStep:
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Utgang til skjema / søknad / klage
           */
          external: {
            /**
             * Ekstern URL til søknad eller liknende
             */
            externalUrl?: string;
          };
        }
      | {
          /**
           * Selected
           */
          _selected: "next";

          /**
           * Nytt steg
           */
          next: {
            /**
             * Redaksjonelt innhold ovenfor valgene
             */
            editorial?: string;

            /**
             * Steg
             */
            steps: Array<{
              /**
               * Tittel på valget
               */
              label: string;

              /**
               * Ekstra forklaring
               */
              explanation?: string;

              /**
               * Ekstern URL til søknad eller liknende
               */
              externalUrl?: string;
            }>;
          };
        };
  }>;
}
