// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FormsOverview {
  /**
   * Side-tittel
   */
  title: string;

  /**
   * Ingress/beskrivelse
   */
  ingress: string;

  /**
   * Målgruppe
   */
  audience:
    | {
        /**
         * Selected
         */
        _selected: "person";

        /**
         * Privatperson
         */
        person: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "employer";

        /**
         * Arbeidsgiver
         */
        employer: Record<string, unknown>;
      }
    | {
        /**
         * Selected
         */
        _selected: "provider";

        /**
         * Samarbeidspartner
         */
        provider: {
          /**
           * Sidetype
           */
          pageType:
            | {
                /**
                 * Selected
                 */
                _selected: "form-details";

                /**
                 * Skjemaoversikt
                 */
                "form-details": {
                  /**
                   * Velg underkategori
                   */
                  provider_audience: "doctor" | "dentist" | "optician" | "occupational_therapist" | "aid_supplier" | "measures_organizer" | "administrator" | "municipality" | "other";
                };
              }
            | {
                /**
                 * Selected
                 */
                _selected: "audience-landing";

                /**
                 * Inngang til underkategorier
                 */
                "audience-landing": Record<string, unknown>;
              };
        };
      };

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath: string;

  /**
   * Vis fritekst-filter
   */
  showFilter: boolean;

  /**
   * Velg eier
   */
  owner: Array<"ytelsesavdelingen" | "arbeids_og_tjenesteavdelingen" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet" | "hr_avdelingen" | "juridisk_avdeling" | "kunnskapsavdelingen" | "kommunikasjonsavdelingen" | "okonomi" | "statistikk" | "hjelpemidler_og_tilrettelegging" | "kontaktsenteret" | "team_personbruker" | "it_avdelingen" | "fylke" | "hjelpemiddelsentralen" | "arbeidslivssenter" | "min_side" | "direktoratet" | "annet">;

  /**
   * Oppsummering
   */
  description?: string;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: Array<string>;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i søk
   */
  noindex: boolean;

  /**
   * -
   */
  "form-details-list"?: undefined;
}
