// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface GlobalValueConfig {
  /**
   * Velg verdi
   */
  key: string;

  /**
   * -
   */
  value?: ;
}
