// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AnimatedIcons {
  /**
   * Velg ikoner
   */
  icons: Array<{
    /**
     * Velg ikon
     */
    icon?: string;

    /**
     * Start-transformasjon
     */
    transformStart?: string;

    /**
     * Slutt-transformasjon
     */
    transformEnd?: string;

    /**
     * Origo
     */
    transformOrigin?: string;
  }>;

  /**
   * Lottie-animasjon ved hover
   */
  lottieHover?: string;

  /**
   * Lottieanimasjon ved klikk (active)
   */
  lottieActive?: string;
}
