// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type PhoneLink = {
  /**
   * Lenketekst
   */
  text: string;

  /**
   * Telefonnummer
   */
  phoneNumber: string;

  /**
   * Lenke med chevron
   */
  chevron: boolean;
}
