// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Overview = {
  /**
   * Sett side-tittel
   */
  title?: string;

  /**
   * Tittel for utlisting og sortering
   */
  sortTitle?: string;

  /**
   * Norsk tittel (hvis fremmedspråklig innhold)
   */
  norwegianTitle?: string;

  /**
   * Ingress
   */
  ingress: string;

  /**
   * Målgruppe
   */
  audience: Array<"person" | "employer" | "provider"> | "person" | "employer" | "provider";

  /**
   * Type oversiktsside
   */
  overviewType: "rates" | "payout_dates" | "processing_times" | "all_products";

  /**
   * Velg fallback data
   */
  localeFallback?: Array<string> | string;

  /**
   * Velg innhold som ikke skal vises i denne oversikten
   */
  excludedContent?: Array<string> | string;

  /**
   * Velg piktogram
   */
  illustration: string;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath: string;

  /**
   * Velg eier
   */
  owner: Array<"arbeids_og_tjenesteavdelingen" | "arbeidsavdelingen_arbeid_helse" | "arbeidsavdelingen_arbeidsgivertjenester" | "arbeidsavdelingen_arbeidsmarkedstiltak" | "arbeidsavdelingen_arbeidsoppfolging" | "avdeling for brukeropplevelse" | "hr_avdelingen" | "direktoratet" | "juridisk_avdeling" | "kommunikasjonsavdelingen" | "kunnskapsavdelingen" | "statistikk" | "klageinstans" | "it_avdelingen" | "velferdsavdelingen_hjelpemidler" | "velferdsavdelingen_sosiale_tjenester" | "ytelsesavdelingen" | "ytelsesavdelingen_arbeidsavklaringspenger" | "ytelsesavdelingen_arbeidsytelser" | "ytelsesavdelingen_familieytelser" | "ytelsesavdelingen_helseytelser" | "ytelsesavdelingen_kontroll" | "ytelsesavdelingen_pensjon" | "okonomi" | "annet" | "arbeidslivssenter" | "hjelpemiddelsentralen" | "hjelpemidler_og_tilrettelegging" | "fylke" | "kontaktsenteret" | "min_side" | "team_personbruker" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet"> | "arbeids_og_tjenesteavdelingen" | "arbeidsavdelingen_arbeid_helse" | "arbeidsavdelingen_arbeidsgivertjenester" | "arbeidsavdelingen_arbeidsmarkedstiltak" | "arbeidsavdelingen_arbeidsoppfolging" | "avdeling for brukeropplevelse" | "hr_avdelingen" | "direktoratet" | "juridisk_avdeling" | "kommunikasjonsavdelingen" | "kunnskapsavdelingen" | "statistikk" | "klageinstans" | "it_avdelingen" | "velferdsavdelingen_hjelpemidler" | "velferdsavdelingen_sosiale_tjenester" | "ytelsesavdelingen" | "ytelsesavdelingen_arbeidsavklaringspenger" | "ytelsesavdelingen_arbeidsytelser" | "ytelsesavdelingen_familieytelser" | "ytelsesavdelingen_helseytelser" | "ytelsesavdelingen_kontroll" | "ytelsesavdelingen_pensjon" | "okonomi" | "annet" | "arbeidslivssenter" | "hjelpemiddelsentralen" | "hjelpemidler_og_tilrettelegging" | "fylke" | "kontaktsenteret" | "min_side" | "team_personbruker" | "arbeid_og_ytelser_styringsenhet" | "familie_og_pensjonsytelser_styringsenhet";

  /**
   * Velg forvalter
   */
  "managed-by"?: Array<"arbeid_ytelser_styringsenhet" | "arbeidslivssenter" | "digisos" | "familie_pensjonsytelser_styringsenhet" | "fylke" | "hjelpemiddelsentralen" | "hjelpemidler_styringsenhet" | "kjernegruppe_aap" | "kjernegruppe_dagpenger" | "kjernegruppe_ekspertbistand" | "kjernegruppe_familie" | "kjernegruppe_hjelpemidler" | "kjernegruppe_medlemskap" | "kjernegruppe_oppfolging" | "kjernegruppe_ortopediske_hjelpemidler" | "kjernegruppe_pensjon" | "kjernegruppe_sosiale_tjenester" | "kjernegruppe_spraktolk" | "kjernegruppe_sykepenger" | "kjernegruppe_tiltak" | "kjernegruppe_tiltakspenger" | "kjernegruppe_uforetrygd" | "kjernegruppe_yrkesskade" | "nav_kontaktsenter_styringsenhet" | "team_minside" | "team_navno" | "po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver"> | "arbeid_ytelser_styringsenhet" | "arbeidslivssenter" | "digisos" | "familie_pensjonsytelser_styringsenhet" | "fylke" | "hjelpemiddelsentralen" | "hjelpemidler_styringsenhet" | "kjernegruppe_aap" | "kjernegruppe_dagpenger" | "kjernegruppe_ekspertbistand" | "kjernegruppe_familie" | "kjernegruppe_hjelpemidler" | "kjernegruppe_medlemskap" | "kjernegruppe_oppfolging" | "kjernegruppe_ortopediske_hjelpemidler" | "kjernegruppe_pensjon" | "kjernegruppe_sosiale_tjenester" | "kjernegruppe_spraktolk" | "kjernegruppe_sykepenger" | "kjernegruppe_tiltak" | "kjernegruppe_tiltakspenger" | "kjernegruppe_uforetrygd" | "kjernegruppe_yrkesskade" | "nav_kontaktsenter_styringsenhet" | "team_minside" | "team_navno" | "po_aap" | "po_arbeid" | "po_familie" | "po_helse" | "po_pensjon" | "po_arbeidsgiver";

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string> | string;

  /**
   * Fant du det du lette etter?
   */
  feedbackToggle: boolean;

  /**
   * Chatbot Frida
   */
  chatbotToggle: boolean;

  /**
   * Oppsummering
   */
  description?: string;

  /**
   * Nøkkelord (internt søk)
   */
  keywords?: Array<string> | string;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i søk
   */
  noindex: boolean;

  /**
   * Ikke vis "tilfeldige" utdrag (snippets) i Google-søk
   */
  nosnippet: boolean;

  /**
   * (tomt felt, skal ikke brukes)
   */
  allProducts?: string;
};
