// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface FormDetailsLink {
  /**
   * Lenke til skjema
   */
  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Lenke til mellomsteg
         */
        internal: {
          /**
           * Velg mellomsteg
           */
          target: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * Direkte lenke til skjema
         */
        external: {
          /**
           * URL
           */
          url: string;
        };
      };
}
