// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AreapageSituationCardPartConfig {
  /**
   * Situasjon (settes automatisk)
   */
  dummyTarget: string;

  /**
   * Skjul denne situasjonen
   */
  disabled: boolean;
}
