// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface VideoConfig {
  /**
   * Video-innhold
   */
  targetContent: string;

  /**
   * Overstyr språk for undertekster
   */
  language?: string;

  /**
   * Beskrivende tittel
   */
  title?: string;

  /**
   * Brukes ikke: URL til video
   */
  video?: string;
}
