// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface VideoConfig {
  /**
   * URL
   */
  video: string;

  /**
   * Beskrivende tittel
   */
  title: string;
}
