name: Build, test and deploy app
on:
  workflow_call:
    inputs:
      naisCluster:
        required: true
        type: string
      xpAdminHost:
        required: true
        type: string
      xpEnv:
        required: true
        type: string
      xpVersion:
        required: true
        type: string
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build-app:
    name: Build app
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
    with:
      environment: ${{ inputs.xpEnv }}
      xpVersion: ${{ inputs.xpVersion }}
  e2e-tests:
    name: Run e2e tests
    uses: ./.github/workflows/.run-e2e-tests.yml
    needs: build-app
    permissions:
      contents: read
    with:
      buildArtifact: ${{ needs.build-app.outputs.buildArtifact }}
  build-deploy-image:
    name: Build deploy image
    uses: ./.github/workflows/.build-deploy-image.yml
    needs: build-app
    permissions:
      contents: read
      id-token: write
    with:
      buildArtifact: ${{ needs.build-app.outputs.buildArtifact }}
      imageSuffix: ${{ inputs.xpEnv }}
      xpVersion: ${{ inputs.xpVersion }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  deploy:
    name: Deploy app
    uses: ./.github/workflows/.deploy-with-naisjob.yml
    needs: [build-deploy-image, e2e-tests]
    permissions:
      contents: read
      id-token: write
    with:
      image: ${{ needs.build-deploy-image.outputs.image }}
      naisCluster: ${{ inputs.naisCluster }}
      xpAdminHost: ${{ inputs.xpAdminHost }}
      xpEnv: ${{ inputs.xpEnv }}