name: Build application
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      xpVersion:
        required: true
        type: string
    outputs:
      buildArtifact:
        description: "nav.no app jar"
        value: ${{ jobs.build.outputs.buildArtifact }}

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      buildArtifact: navno-jar-${{inputs.environment}}-${{github.sha}}
    outputs:
      buildArtifact: ${{ env.buildArtifact }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'gradle'
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install node.js dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Build application
        run: ./gradlew build -PxpVersion=${{ inputs.xpVersion }}
      - name: Build e2e test data
        run: ./gradlew build -p=e2e-tests/.xp-test-data-app -PxpVersion=${{ inputs.xpVersion }}
      - name: Upload jar files
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: ${{ env.buildArtifact }}
          path: |
            build/libs/navno.jar
            e2e-tests/.xp-test-data-app/build/libs/navno-testdata.jar
          overwrite: 'true'
          retention-days: 1
