name: Run e2e tests
on:
    workflow_call:
        inputs:
            buildArtifact:
                required: true
                type: string

jobs:
    tests:
        name: Run tests
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            - name: Setup pnpm
              uses: pnpm/action-setup@v5
            - name: Setup node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: 'pnpm'
            - name: Install node.js dependencies
              run: pnpm install --frozen-lockfile
            - name: Download jar files
              uses: actions/download-artifact@v8
              with:
                  name: ${{ inputs.buildArtifact }}
            - name: Build test assets
              run: pnpm --filter nav-enonicxp-e2e-tests run prepare-gha
            - name: Run tests
              run: pnpm --filter nav-enonicxp-e2e-tests run test
