name: Build image for deploy job
on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
    outputs:
      image:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build application
        run: |
          gradle clean build deploy
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          dockerfile: .nais-deploy-job/Dockerfile
          image_suffix: ${{ inputs.imagename }}
          build_args: |
            appFileName=navno.jar
