name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Define variables
        id: vars
        run: |
          echo ::set-output name=VERSION::$(git tag  | sed 's/.*\(v[0-9].[0-9].[0-9]\).*/\1/p' | sort -V | tail -1)-$(echo ${GITHUB_SHA::7})
      - name: Fetch url lookup table from nav-enonicxp-iac
        run: |
          curl \
            --output url-lookup.json \
            --header "Authorization: Bearer ${{ secrets.GITHUB_PAT }}" \
            --header "Accept: application/vnd.github.v3.raw" \
            --location "https://api.github.com/repos/navikt/nav-enonicxp-iac/contents/url-lookup/q6.json"
          echo "$(cat url-lookup.json)"
          mkdir -p src/main/resources/assets/iac && cp url-lookup.json "$_"
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build application
        id: build
        run: |
          version=${{ steps.vars.outputs.VERSION }}
          gradle clean build deploy -Pversion=${version//v}
      - uses: actions/upload-artifact@v1
        with:
          name: Application
          path: build/libs
