name: Build deploy job image
on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string

jobs:
  build:
    name: Build deploy job image
    runs-on: ubuntu-latest
    env:
      image: ghcr.io/${{ github.repository }}:${{ inputs.imagename }}-${{ github.sha }}
    outputs:
      image: ${{ env.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build application
        id: build
        run: |
          gradle clean build deploy
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker build -f .nais-deploy-job/Dockerfile -t ${{ env.image }} --build-arg APP_FILE_NAME="navno.jar" .
          docker push ${{ env.image }}