name: Build and test on PR
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build app
    uses: ./.github/workflows/build-app.yml
    permissions:
      contents: read
    with:
      environment: pr
      xpVersion: "7.14.2"
  e2e-tests:
    name: Run e2e tests
    uses: ./.github/workflows/e2e-tests.yml
    needs: build
    with:
      buildArtifact: ${{ needs.build.outputs.buildArtifact }}