name: Deploy job test
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to nais k8s
    runs-on: ubuntu-latest
    environment: dev-sbs:personbruker
    env:
      image: ghcr.io/${{ github.repository }}:deploy-test-${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker build -f .nais/Dockerfile -t ${{ env.image }} .
          docker push ${{ env.image }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/deploy-job.yml
          VAR: image=${{ env.image }},xpAdminHost=portal-admin-dev.oera.no,xpAdminInstallServicePath=/admin/rest/app/install,