name: Deploy to dev
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to dev
    uses: ./.github/workflows/.build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      naisCluster: dev-gcp
      xpAdminHost: portal-admin-dev.oera.no
      xpEnv: dev1
      xpVersion: '7.14.4'
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}