name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  deploy:
    name: Deploy to prod
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/.build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      naisCluster: prod-gcp
      xpAdminHost: portal-admin.oera.no
      xpEnv: prod
      xpVersion: '7.14.4'
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}