name: Deploy to dev2/q6
on: workflow_dispatch

jobs:
  deploy-to-dev2:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Deploy to dev2/q6
        uses: ./.github/actions/build-and-deploy
        with:
          naisCluster: dev-gcp
          xpAdminHost: portal-admin-q6.oera.no
          xpEnv: q6
          xpVersion: '7.14.4'
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}