name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to prod
    uses: ./.github/workflows/.build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      naisCluster: prod-gcp
      xpAdminHost: portal-admin.oera.no
      xpEnv: prod
      xpVersion: '7.14.4'
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  release:
    name: Create a new release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Generate release tag
        run: |
          if [[ "${{ github.head_ref }}" != "" ]]; then
            echo "TAG_NAME=pr-${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=release-${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: main
          tag_name: ${{ env.TAG_NAME }}
          name: "Release for ${{ env.TAG_NAME }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions