name: Deploy job test
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to nais k8s
    runs-on: ubuntu-latest
    environment: dev-sbs:personbruker
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/deploy-job.yml
          VAR: xpAdminHost=portal-admin-dev.oera.no,xpAdminInstallServicePath=/admin/rest/app/install,
