name: Deploy to dev
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Deploy to dev
        uses: ./.github/actions/build-and-deploy
        with:
          naisCluster: dev-gcp
          xpAdminHost: portal-admin-dev.oera.no
          xpEnv: dev1
          xpVersion: '7.14.4'
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}