name: Deploy to dev2/q6
on:
  workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/build-deploy-image.yml
    with:
      imagename: 'q6-deploy'
  deploy:
    uses: ./.github/workflows/deploy-with-naisjob.yml
    needs: build
    with:
      naisCluster: dev-gcp
      xpAdminHost: portal-admin-q6.oera.no
      image: ${{ needs.build.outputs.image }}
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}