name: Deploy job test
on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy to nais k8s
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/deploy-job.yml
          VAR: xpAdminHost=www.nav.no
