name: Deploy to dev
on:
  workflow_dispatch

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/build-deploy-image.yml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    with:
      imagename: 'dev-deploy'
      xpVersion: '7.14.0'
  deploy:
    uses: ./.github/workflows/deploy-with-naisjob.yml
    needs: build
    with:
      naisCluster: dev-gcp
      xpAdminHost: portal-admin-dev.oera.no
      xpEnv: dev1
      image: ${{ needs.build.outputs.image }}
    secrets:
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}