name: Deploy to prod
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to prod
    uses: ./.github/workflows/.build-and-deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      naisCluster: prod-gcp
      xpAdminHost: portal-admin.oera.no
      xpEnv: prod
      xpVersion: '7.14.4'
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  release:
    name: Create a new release
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: "!contains(github.event.head_commit.modified, 'README.md')"
    steps:
      - name: Generate unique tag name
        run: echo "TAG_NAME=$(date +%s)" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: main
          tag_name: release/prod@${{ env.TAG_NAME }} # Generates a unique tag using timestamp
          name: Release ${{ github.head_ref }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # This is a PAT with repo permissions