name: Run tests on PR
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build app
    uses: ./.github/workflows/.build-app.yml
    permissions:
      contents: read
    with:
      environment: pr
      # Should use the current prod version
      xpVersion: "7.14.4"

  e2e-tests:
    name: Run e2e tests
    uses: ./.github/workflows/.run-e2e-tests.yml
    needs: build
    permissions:
      contents: read
    with:
      buildArtifact: ${{ needs.build.outputs.buildArtifact }}