// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicNewsListPartConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Innholdsliste for nyheter
   */
  contentList: {
    /**
     * Maks antall lenker som vises
     */
    numLinks?: number;

    /**
     * Velg innholdsliste
     */
    target: string;
  };

  /**
   * Flere nyheter
   */
  moreNews?: {
    /**
     * Lenke
     */
    url: string;

    /**
     * Lenketekst
     */
    text: string;
  };

  /**
   * Utvidbar
   */
  expandable: boolean;

  /**
   * Utvidet som standard
   */
  expandableOpenByDefault: boolean;

  /**
   * Tittel på utvidbart panel
   */
  expandableTitle?: string;

  /**
   * Anker-id på utvidbart panel
   */
  expandableAnchorId?: string;

  /**
   * Velg visning
   */
  renderOnAuthState: "always" | "loggedIn" | "loggedOut";
}
