// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface DynamicNewsListConfig {
  /**
   * Tittel
   */
  title?: string;

  /**
   * Innholdsliste for nyheter
   */
  contentList: {

  };

  /**
   * Flere nyheter
   */
  moreNews?: {
    /**
     * Lenke
     */
    url: string;

    /**
     * Lenketekst
     */
    text: string;
  };
}
