// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface AreaPage {
  /**
   * Målgruppe
   */
  audience: "person" | "employer" | "provider" | "self_employed";

  /**
   * Område
   */
  area: "work" | "family" | "health" | "accessibility" | "pension" | "social_counselling";

  /**
   * Overskrift
   */
  header: string;

  /**
   * Banner
   */
  banner?: {

    link:
      | {
          /**
           * Selected
           */
          _selected: "internal";

          /**
           * Intern lenke
           */
          internal: Record<string, unknown>;
        }
      | {
          /**
           * Selected
           */
          _selected: "external";

          /**
           * Ekstern lenke
           */
          external: Record<string, unknown>;
        };

    /**
     * Velg farge
     */
    color: string;

    /**
     * Innhold
     */
    html?: string;
  };

  /**
   * Velg områder
   */
  areasRefs?: Array<string>;

  /**
   * Skriv inn ønsket kort-url
   */
  customPath?: string;

  /**
   * Legg til andre språkversjoner
   */
  languages?: Array<string>;

  /**
   * Fant du det du lette etter?
   */
  feedbackToggle: boolean;

  /**
   * Chatbot Frida
   */
  chatbotToggle: boolean;

  /**
   * Oppsummering
   */
  description?: string;

  /**
   * Sidebeskrivelse for søk og sosiale medier
   */
  metaDescription?: string;

  /**
   * Canonical url - NB! Skal bare legges inn av hovedredaktør/administrator
   */
  canonicalUrl?: string;

  /**
   * Skal ikke vises i eksternt søk
   */
  noindex: boolean;
}
