import { NAVNO_ROOT_PATH } from '../../constants';

// Queries are executed by the Guillotine app, via an internal vhost mapping to its endpoint
// (/site/<project>/<branch>). Requests are authenticated with the service secret (see idprovider.ts)
export const GUILLOTINE_API_URL =
    app.config.guillotineApiUrl || 'http://localhost:8080/_guillotine';

const GUILLOTINE_API_BASE_PATH = GUILLOTINE_API_URL.replace(/^https?:\/\/[^/]+/, '');

const escapeRegExp = (str: string) => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// URLs generated by the Guillotine app are prefixed with the loopback endpoint path
// (<base>/<project>/<branch>). With lib-guillotine in XP7, URLs were generated relative to the
// public site vhost. Rewrite to match that format:
// <base>/<project>/<branch>/www.nav.no/some/path -> /some/path
// <base>/<project>/<branch>/_/media:image/...    -> /_/media:image/...
const loopbackPrefixPattern = `${escapeRegExp(GUILLOTINE_API_BASE_PATH)}/[^/"\\\\]+/(?:draft|master)`;
const loopbackSiteUrlRegex = new RegExp(
    `${loopbackPrefixPattern}${escapeRegExp(NAVNO_ROOT_PATH)}(?:/|(?=["?#\\\\]))`,
    'g'
);
const loopbackApiUrlRegex = new RegExp(`${loopbackPrefixPattern}/_/`, 'g');

export const rewriteLoopbackUrls = (str: string) =>
    str.replace(loopbackSiteUrlRegex, '/').replace(loopbackApiUrlRegex, '/_/');
